### PR TITLE
Add aarch64 support

### PR DESCRIPTION
**Pull request by yselkowitz**
This makes the cluster-samples-operator fully functional on aarch64 
(arm64 in Go parlance).  The revendoring is necessary to pick up 
https://github.com/openshift/api/pull/759.

### CODE REVIEW

**Comment by gabemontero** [comment]
heads up @yselkowitz ... I've got a non-trivial refactor of samples operator cooking with https://github.com/openshift/cluster-samples-operator/pull/313

My initial scan of your changes (in particular https://github.com/openshift/cluster-samples-operator/pull/335/commits/1a3146dea2ad1a69b95d73eab3ad4aa55e758ffc) gives me confidence that these PRs will not hit conflicts.  But that said, I will try to avoid having to rebase my PR if I can help it.

I'm awaiting a review from @adambkaplan as I type ... if all goes OK, it should still be sometime next week when we can pull this in.  And if a rebase here is needed, I would think it would be pretty straight forward given the simplicity of the changes you have in https://github.com/openshift/cluster-samples-operator/pull/335/commits/1a3146dea2ad1a69b95d73eab3ad4aa55e758ffc

thanks

**Review by adambkaplan — APPROVED** [review]
/approve

**Comment by adambkaplan** [comment]
/hold

Per @gabemontero 's comment regarding the refactor. If we're not waiting on this any more, then Gabe you can go ahead and add the lgtm.

**Comment by gabemontero** [comment]
OKD was working to some degree on Friday ... let's see how it is here.  If it flakes for generic enough reasons, I'll override

Also, depending on how the build-125 review progresses or does not progress today, I'll merge this by EOB and deal with any rebase issues there if need be tomorrow.

**Comment by gabemontero** [comment]
/hold cancel

/lgtm

/retest

I'll override any justifiably overriden OKD flakes but we'll give them one more go

**Pull request merged**
