### PR TITLE
JNKS-254: remove imagestream manifest refs; remove override of jenkins images with payload images

### PR DESCRIPTION
**Pull request by gabemontero**
includes a "temp" bump of the jenkins imagestreams where we use the TBR (registry.redhat.io) references to the OCP jenkins images (which  differ from the OCP install payload image references).

### CODE REVIEW

**Comment by gabemontero** [comment]
still a lot of bad luck around aws route53

/test e2e-aws-operator

**Comment by gabemontero** [comment]
A problem with the imagestream json file for the base agent:

```
2022-03-28T14:31:46.759585285Z time="2022-03-28T14:31:46Z" level=info msg="processing file jenkins-agent-base-rhel.json from dir /opt/openshift/operator/x86_64/jenkins/imagestreams"
2022-03-28T14:31:46.759614381Z time="2022-03-28T14:31:46Z" level=info msg="invalid character '}' looking for beginning of object key string error reading file [/opt/openshift/operator/x86_64/jenkins/imagestreams/jenkins-agent-base-rhel.json]"
2022-03-28T14:31:46.759633722Z time="2022-03-28T14:31:46Z" level=info msg="error processing content : invalid character '}' looking for beginning of object key string"

```

will bring up a cluster, sort that out and then update this PR.

**Comment by gabemontero** [comment]
etcd flake but samples upgraded successfully in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/416/pull-ci-openshift-cluster-samples-operator-master-e2e-aws-upgrade/1509880869047767040

**Comment by gabemontero** [comment]
OK great news:  I was able to invoke an upgrade test via cluster-bot at https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1509972517186441216 where
- start at 4.10.6
- go to 4.11 plus this PR

And the jenkins related imagestreams are exactly what we planned/wanted:
- the jenkins and jenkins-agent-base imagestreams are updated and point to the registry.redhat.io images specified (these will ultimately be the CPaas images when they are ready
- the jenkins-agent-maven and jenkins-agent-nodejs imagestreams still exist, but as we are not producing CPaas images for those, they stay at the 4.10.6 level of those images; once we sort out the deprecation cycle with PM, we can add code in a future release that deletes those imagestreams when those images are EOL

We are now at the point where if we think the CPaas images will be ready relatively soon, we could merge this PR.  My only fear is merging this PR, and then decide the CPaas images cannot make 4.11 because we find bugs in them that can't be resolved in time.

@akram @jkhelil @adambkaplan @jitendar-singh FYI

**Comment by adambkaplan** [comment]
See also https://github.com/openshift/jenkins/pull/1414 - we should give a thumbs up/down with these two PRs.

**Comment by gabemontero** [comment]
/assign @rolfedh 

for docs approved label

reminder @rolfedh - my google doc for citing what needs to be changed in the docs is at https://docs.google.com/document/d/1ihYNy_j7rZkH_K-Oducv43hDXBnJ0G_jRlTHhgZ1-YM/edit#

**Comment by gabemontero** [comment]
/assign @jitendar-singh 

for qe approved label

see prior comments to you in https://issues.redhat.com/browse/JKNS-260 for test plan 
where you have already applied the approve label there, and we are waiting on approve of https://issues.redhat.com/browse/JKNS-282

**Comment by gabemontero** [comment]
/label px-approved

Rick Wagner approved in Jira

**Review by rolfedh — APPROVED** [review]

**Comment by gabemontero** [comment]
/label docs-approved

@rolfedh just did a git approve

**Comment by gabemontero** [comment]
/label qe-approved

@jitendar-singh approved in Jira

**Comment by gabemontero** [comment]
OK I've updated this PR with the official content from openshift/jenkins -> openshift/library

I'll boot up a cluster-bot cluster with it and assuming the imagestreams look at expected, and the e2e's are OK, I'll report back here and we'll see about releasing the hold and tagging for merge

**Comment by gabemontero** [comment]
just confirmed with @jkhelil that the CPaaS team has asked us to hold off on cutting the errata for @akram 's update until April 21.

**Comment by gabemontero** [comment]
> just confirmed with @jkhelil that the CPaaS team has asked us to hold off on cutting the errata for @akram 's update until April 21.

@akram and @jkhelil informed us today that the publishing of the new errata is in progress

we are monitoring https://catalog.redhat.com/software/containers/ocp-tools-4/jenkins-rhel8/5fe1f38288e9c2f788526306?tag=all to see when it arrives

when it does, I'll do a quick check of it, and then update this PR, as well as make an update to openshift/jenkins, to use the new cpaas image

**Comment by gabemontero** [comment]
@jitendar-singh - I've done some book keeping in https://issues.redhat.com/browse/JKNS-282 around the conceivable testing, consolidating some prior posts and conversations there.

In particular, the new imagestreamstags for providing more options around upgrade of jenkins is an item that I want to make sure you understand and are comfortable with before we merge this last piece of switching jenkins from the ocp payload images to the cpaas images.  For these, I'm not sure if you were aware of them when you approved JKNS-282.

Post any questions or comments you have in which ever channel works for you, and I'll make sure you are good with everything before we merge this.

**Comment by gabemontero** [comment]
quay.io pruning means we need to handle the sha specific tag for OKD a bit differently.... the one from a couple of weeks ago is now gone

**Comment by gabemontero** [comment]
ok okd e2e aws jenkins passed at https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/416/pull-ci-openshift-cluster-samples-operator-master-okd-e2e-aws-jenkins/1518412259129298944

the rest are unrelated flakes

/skip

**Comment by gabemontero** [comment]
ok @jitendar-singh confirmed in scrum that his QE approval did include the new imagestreamtags I added to provide different upgrade behaviors

/assign @coreydaley 
/assign @akram 
/assign @jkhelil 

assuming we get green e2e's in the remaining tests (should get them, the last failures were just unrelated flakes) this is ready for merge

@adambkaplan FYI

**Pull request closed without merging**
