### PR TITLE
WIP Bug 1813894: Stop using service ca from service account token

### PR DESCRIPTION
**Pull request by marun**
Before it will be ready to merge, this PR requires:
 - [ ] updates to the [redhat-sso-7-openshift-image](https://github.com/jboss-container-images/redhat-sso-7-openshift-image) repo
   - [ ] https://github.com/jboss-container-images/redhat-sso-7-openshift-image/pull/145
   - [ ] https://github.com/jboss-container-images/redhat-sso-7-openshift-image/pull/146
 - [ ] an update to the [openshift/library](https://github.com/openshift/library) repo
   - [ ] https://github.com/openshift/library/pull/219
 - [ ] an update to this PR to incorporate the openshift-library changes

/cc @sttts @mfojtik @deads2k

### CODE REVIEW

**Comment by gabemontero** [comment]
@marun - the methodology we employ is to create a PR in https://github.com/openshift/library for these changes

Please help me if I missed it but I don't see a PR from you (either opened or closed) for this.

Once validated and merged there, we'll then pick into this repo.

I will note that there are syntax errors in the content you provided, which is why the various e2e's failed.

From the samples operator logs from one of the e2e's:
```
time="2020-05-13T05:58:54Z" level=info msg="invalid character ':' after array element error reading file [/opt/openshift/operator/ocp-x86_64/sso/templates/sso73-x509-postgresql-persistent.json]"
time="2020-05-13T05:58:54Z" level=info msg="error processing content : invalid character ':' after array element"
time="2020-05-13T05:58:54Z" level=info msg="CRDUPDATE proc file err update"
```

If you have not already, I would suggest attempting to manually create the template / imagestreams you are modifying in an existing openshift cluster as a sanity check for your changes.

/hold

**Comment by marun** [comment]
@gabemontero Thank you for your prompt response!

> the methodology we employ is to create a PR in https://github.com/openshift/library for these changes
> 
> Please help me if I missed it but I don't see a PR from you (either opened or closed) for this.

I appreciate the confirmation, I surmised as much shortly after posting this PR. As per the leading comment, I've proposed PRs to the `jboss-container-images/redhat-sso-7-openshift-image` repo upstream of `openshift/library`. I'll update this PR once the changes land in `openshift/library`.

**Comment by gabemontero** [comment]
@marun - with your openshift/library PR up, I would suggest we close this PR and let me go through the normal process of updating samples (where I'll just update the ones you changed) ... there are some flakes / bugs in other samples that need to be worked around.  It would be easier for me to do that vs. explaining it to you.

What do you think?

**Comment by marun** [comment]
> @marun - with your openshift/library PR up, I would suggest we close this PR and let me go through the normal process of updating samples (where I'll just update the ones you changed) ... there are some flakes / bugs in other samples that need to be worked around. It would be easier for me to do that vs. explaining it to you.
> 
> What do you think?

Makes sense to me!

**Pull request closed without merging**
