### PR TITLE
Bug 1898745: deprecate ImageChangesInProgress, make sure it stays false

### PR DESCRIPTION
**Pull request by gabemontero**
/hold 

during the analysis of upgrade issues exposed via search.ci that lead to https://github.com/openshift/cluster-samples-operator/pull/340

another simplification occurred to me that goes with our move off of tracking conditions on the samples operator cluster scoped config resource  .... deprecating the `ImageChangesInProgress` condition and use the newer approaches for tracking imagestream status, as well as the approach started in 4.6 of not gating the report of being ready to the CVO, namely
- active == true
- progressing == false
- degraded == false
- version set
on the state of imagestreams after we have created them (i.e. their imports do not gate the process)

Now, so far (after about 15 hours),  since #340 merged, the samples upgrade has appeared clean on search.ci, so I'm not chomping at the bit to merge this.

Minimally, I want to get a longer sample size.  If some more flakes show up in the coming days, and it looks like this change will help, we'll go sooner.

Otherwise, it is a judgement call with the team as to whether we go with this before 4.7 DCUT, or wait until 4.8.

But long term, I really like this simplification.  And it continues along the pivoting we've been doing with samples since we've come to the agreement that tying imports and dependencies on registry.redhat.io does not lend well to CVO status.

@pedjak - this PR, and my notes above, might provide educational value to your team as we move closer to transitioning.  It touches on the recent changes I mentioned today, as well as some of the key concepts, with respect to both how this operator deals with its operands, as well as how it reports to its operator, the CVO.  Could be worth you all taking a look as part of your educational cycles.

### CODE REVIEW

**Comment by gabemontero** [comment]
@pedjak - the other PRs besides #340  that have been part of this 4.7 simplification / maintainability effort are 

- https://github.com/openshift/cluster-samples-operator/pull/338
- https://github.com/openshift/cluster-samples-operator/pull/313

@adambkaplan @coreydaley - check out this PR's description if you have cycles ... I'll also touch upon this in our next scrum.

**Comment by gabemontero** [comment]
/test okd-unit 

(well known metric port conflict flake)

**Comment by gabemontero** [comment]
I saw one more failure profile overnight in one particular periodic, along with a rehearsal job related to that periodic.

key particulars:  APIServerConflictError (on the samples exist update / samples config crd resource)
and a "fatal error: concurrent map iteration and map write" in the pod logs

from the search:  matched 0.09% of failing runs and 0.43% of jobs
over thousands of runs.

this PR, with the setting of available/progressing/version immediately, should mitigate the first item.  The second commit addresses the second.

I'll bring up in scrum today and we'll decide on who to review, etc.

/test e2e-aws-upgrade
(get a few more green runs)
/retest
(get past unrelated flakes)

**Comment by gabemontero** [comment]
some docker.io throttling and unrelated flakes in e2e-aws and okd-e2e-aws

first additional upgrade e2e passsed

/test e2e-aws-upgrade
/test e2e-aws

**Comment by gabemontero** [comment]
several components failed in upgrade job https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/341/pull-ci-openshift-cluster-samples-operator-master-e2e-aws-upgrade/1329438645215563776 but I have confirmed `openshift-samples` was not one of them

**Comment by wking** [comment]
> ... as well as the approach started in 4.6 of not gating the report of being ready to the CVO ...

Do we have CI test-cases that depend on the imports having succeeded?  Because if folks are relying on the imports, and the imports fail or are slow, and the tests fail, but the samples operator is saying "no problems on my end", I expect there will be some confusion ;).

On the other hand, I'd also be fine with samples claiming it was happy regardless of import success, as long as any samples-consuming tests (there may be none) have their own checks for import success, and we can reasonably expect any other samples consumers to have their own, similar guards.

**Comment by gabemontero** [comment]
> > ... as well as the approach started in 4.6 of not gating the report of being ready to the CVO ...
> 
> Do we have CI test-cases that depend on the imports having succeeded? Because if folks are relying on the imports, and the imports fail or are slow, and the tests fail, but the samples operator is saying "no problems on my end", I expect there will be some confusion ;).
> 

Yes we do @wking .... but see below ....

> On the other hand, I'd also be fine with samples claiming it was happy regardless of import success, as long as any samples-consuming tests (there may be none) have their own checks for import success, and we can reasonably expect any other samples consumers to have their own, similar guards.

When we moved off of marking samples degraded a release or two ago when imports failed, we augmented the verification we already had around this (which previously figured out if build test x failed cause the ruby imagestream could not import), including adding specific tests that just verified the imports we needed were there, to clearly isolate that root cause.

Good questions, but I think we are good here.  Thanks :-)

**Comment by gabemontero** [comment]
will give okd-e2e-aws one more try, otherwise will override

/test okd-e2e-aws

**Comment by gabemontero** [comment]
yep okd-e2e-aws are unrelated flakes we can skip/override as needed

but let's get a clean run of e2e-aws-builds in addition to okd-e2e-aws-builds

**Comment by gabemontero** [comment]
in case build not being required bypasses things

**Pull request merged**
