### PR TITLE
pull in openshift/library updates

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/sig-developer-experience fyi / ptal

it has been a bit since I pulled in openshift/library updates

@adambkaplan @bparees - please provide your takes on how close to code freeze do we pull in openshift/library content

do we go as far as to say post an update to the openshift/library readme on deadlines for getting samples content into 4.1 GA ?

### CODE REVIEW

**Comment by gabemontero** [comment]
aws vpc quota shortage on e2e-aws-operator run

**Comment by bparees** [comment]
> @adambkaplan @bparees - please provide your takes on how close to code freeze do we pull in openshift/library content

i'd say start shutting it down now...  we shouldn't be accepting new imagestreams at this point and unless there's a specific fix to a broken template, there's probably no reason to pick up template changes either.  Obviously teams can keep pushing out new versions of their images which we'll pick up when the imagestream is imported into the cluster.


> do we go as far as to say post an update to the openshift/library readme on deadlines for getting samples content into 4.1 GA ?

i doubt that's likely to be seen by anyone who matters unfortunately.

**Comment by adambkaplan** [comment]
May 8th is code freeze for GA - if there's any date to pick, that would be it.

**Comment by adambkaplan** [comment]
@bparees per your comment, then I would recommend April 12th as the last day to accept changes (beta 4 code freeze)

**Comment by bparees** [comment]
yeah i'm trying to treat this as a feature freeze.  if it's not fixing a bug, don't update it further.

**Comment by gabemontero** [comment]
On Tue, Apr 9, 2019 at 1:40 PM Ben Parees <notifications@github.com> wrote:

> @adambkaplan <https://github.com/adambkaplan> @bparees
> <https://github.com/bparees> - please provide your takes on how close to
> code freeze do we pull in openshift/library content
>
> i'd say start shutting it down now... we shouldn't be accepting new
> imagestreams at this point and unless there's a specific fix to a broken
> template, there's probably no reason to pick up template changes either.
> Obviously teams can keep pushing out new versions of their images which
> we'll pick up when the imagestream is imported into the cluster.
>
Just to be clear, by shutting it down now, do you mean we should not merge
this PR ?

**Comment by bparees** [comment]
> Just to be clear, by shutting it down now, do you mean we should not merge this PR ?

might as well proceed w/ this one... get one last round in and then lock it down.

**Comment by gabemontero** [comment]
ok cool and that would line up pretty closely with @adambkaplan 's Apr 12th proposal.

**Comment by gabemontero** [comment]
email sent to aos-devel and openshift-sme @adambkaplan

**Comment by gabemontero** [comment]
e2e-aws-image-ecosystem hit a bunch of project setup `Unauthorized`

**Comment by gabemontero** [comment]
per `openshift-dev-helper` the e2e-aws-image-ecosystem  had a machine-config failure on startup:

```machine-config                                              Available=False, Failing=True, Progressing=True```

with multus pain

```multus-nw4d8                                                          Initialized=True, Ready=True, ContainersReady=True, PodScheduled=True
  [!] Container "kube-multus" restarted 2 times, last exit 1 caused by:```

Also saw some image pull failures in the kubelet

**Comment by gabemontero** [comment]
`Unauthorized` and slow dancer build ... trying again

**Comment by gabemontero** [comment]
aws vpc quota pain on e2e-aws-image-ecosystem

/test e2e-aws-image-ecosystem

**Comment by gabemontero** [comment]
machine/network operators did not reach availability in last e2e-aws-operator run

**Comment by gabemontero** [comment]
2 more slow builds with image eco timing out

/test e2e-aws-image-ecosystem

**Pull request merged**
