### PR TITLE
bump samples as part of 4.2 wrap up (including rm eol imgs)

### PR DESCRIPTION
**Pull request by gabemontero**
4.2 freeze bump of openshiift/library content, including all the recent EOL stuff 

@siamaksade @adambkaplan fyi

### CODE REVIEW

**Comment by gabemontero** [comment]
No it won't pick that up until the overnight job runs.

**Comment by gabemontero** [comment]
I can do another update this weekend if you like.

**Comment by gabemontero** [comment]
aws flake e2e eco

**Comment by gabemontero** [comment]
In particular, the ` arch/x86_64/official/....` paths need to get updated to get pulled into the samples operator sync.

**Comment by gabemontero** [comment]
a lot of sig-storage errors in e2e-aws

**Comment by adambkaplan** [comment]
this broke build tests that referenced the EOL Ruby Imagestream - d'oh!

**Comment by gabemontero** [comment]
Ahhhh.  We run image eco out of this repo but not builds.

How do you want to proceed @adambkaplan?

**Comment by adambkaplan** [comment]
@gabemontero I have an old PR that updates the tests to use Ruby 2.5. I can rebase it and go from there.

**Comment by gabemontero** [comment]
cool thanks @adambkaplan 

and I'll see next week about adding e2e-aws-build to cluster-samples-operator, even if just as an optional job

**Pull request merged**
