### PR TITLE
add current profile annotations to CVO manifests

### PR DESCRIPTION
**Pull request by guillaumerose**
This is matches openshift/enhancements#414 and doesn't change existing behavior

### CODE REVIEW

**Comment by gabemontero** [comment]
/approve

will lgtm when tests are green

**Comment by deads2k** [comment]
/lgtm
/hold

holding for @gabemontero 's request for green tests. Feel free to release hold after.

**Comment by gabemontero** [comment]
some network operator degraded cluster install errors are coming in ... will retest for those, but will let the entire initial pass complete first, see if anything of the non-flake variety comes in

**Comment by gabemontero** [comment]
OK have some clean OCP e2e's

Let's see if we can get one clean OKD run and I'll release the hold

/test okd-e2e-aws-operator

**Comment by gabemontero** [comment]
hey @vrutkovs - the network operator / ovn node stuff is consistently crash looping in the okd e2e's (but are clean in the ocp e2e variants)

would you happen to know if this is a known okd issue?

scoping out a couple of the pod logs, I see 

```
I1023 17:35:46.604274   21329 config.go:919] exec: /usr/bin/ovs-vsctl --timeout=15 set Open_vSwitch . external_ids:ovn-nb="ssl:10.0.148.244:9641,ssl:10.0.176.27:9641,ssl:10.0.219.56:9641" => exit status 1
F1023 17:35:46.604318   21329 ovnkube.go:130] error setting OVS external ID 'ovn-nb="ssl:10.0.148.244:9641,ssl:10.0.176.27:9641,ssl:10.0.219.56:9641"': exit status 1
```

I have another samples operator PR running tests now that passed okd e2e's recently ... I'll compare those results with these

if I see the same thing in both PRs, and this appears to be a new okd regression @guillaumerose @deads2k I'll override the okd e2e an try to merge this PR

**Comment by gabemontero** [comment]
yep see the same thing in my BUILD-125 PR

/hold cancel

/override ci/prow/okd-e2e-aws
/override ci/prow/okd-e2e-aws-builds
/override ci/prow/okd-e2e-aws-image-ecosystem
/override ci/prow/okd-e2e-aws-jenkins
/override ci/prow/okd-e2e-aws-operator
/override ci/prow/okd-e2e-aws-upgrade

**Comment by vrutkovs** [comment]
MCO is broken in master, sorry about that :/ 4.6 cherrypicks should work

**Pull request merged**
