### PR TITLE
Bug 1872080: move templates to RHEL/CentOS/UBI 8 imagestream tags

### PR DESCRIPTION
**Pull request by yselkowitz**
This also updates Fuse samples to 7.7.

/assign @gabemontero

### CODE REVIEW

**Comment by gabemontero** [comment]
/approve

waiting on at least some of the multitude of e2e's to come back prior to LGTM

**Comment by gabemontero** [comment]
There is a problem with the mariadb imagestream @yselkowitz pulling `registry.redhat.io/rhel8/mariadb-103:latest` in e2e-aws-image-ecosystem.

```
    - conditions:
      - generation: 2
        lastTransitionTime: "2020-09-03T16:20:25Z"
        message: you may not have access to the container image "registry.redhat.io/rhel8/mariadb-103:latest"
        reason: Unauthorized
        status: "False"
        type: ImportSuccess
      items: null
      tag: 10.3-el8

```

I can pull it locally so it appears to be a registry.redhat.io flake.  I've heard through the grapevine there have been issues pulling images from there today in other PRs / e2e's 

We are going to have to wade through those before getting this merged.

**Comment by yselkowitz** [comment]
Found an issue with dancer-ex
/hold

**Comment by gabemontero** [comment]
seeing if any of the okd e2e's pass (ignoring the still pending upstream dancer-ex change)

/retest

**Comment by yselkowitz** [comment]
Looks like not.  What's the problem?

**Comment by gabemontero** [comment]
hey @vrutkovs  .... in the last  week or so we've seen the OKD e2e's across the board fail with various install/bootstrap types of failures? 

Is this a known situation?

If not, can you take a look at some of the recent failures here and see if some mitigations can be initiated?

If the outlook for fixing this is not "soon", I'm going to be inclined to change the OKD e2e's for samples operator to optional, and override the failures for this PR.

thanks

**Comment by yselkowitz** [comment]
I've pulled in the dotnet template removal from the library, and the dancer template update in advance.  New problem or something wrong with the latest changes?

**Comment by yselkowitz** [comment]
Resynced from the library, picking up the dotnet and dancer changes.
/hold cancel

**Comment by gabemontero** [comment]
for the non-okd's there looks to be CI level unhappiness and the e2e's are not getting off the ground ... we'll just have to wait those out.

if we don't hear from @vrutkovs by this afternoon US eastern time I'll probably pull the trigger on making those OKD jobs optional.

**Comment by yselkowitz** [comment]
Looks like the overall issues have been sorted out, only the OKD tests show as failing now.

**Comment by yselkowitz** [comment]
And it looks like the OKD tests are already optional, there is no (Required) next to any of them.

**Comment by vrutkovs** [comment]
OKD install is broken, feel free to `/skip` those - we'll verify imagestreams are correct later

**Comment by gabemontero** [comment]
> OKD install is broken, feel free to `/skip` those - we'll verify imagestreams are correct later

thanks @vrutkovs 

I now also see the jobs are marked optional in openshift/release 

/skip ci/prow/okd-e2e-aws

**Pull request merged**
