### PR TITLE
OCPBUGS-38157: add mfrancisc and metlos as owners add owners 4.15

### PR DESCRIPTION
**Pull request by mfrancisc**

### CODE REVIEW

**Comment by fbm3307** [comment]
@mfrancisc you would need to add @metlos in openshift org

**Comment by mfrancisc** [comment]
> @mfrancisc you would need to add @metlos in openshift org

I don't think I have permissions to do that. I think he needs to send request for that! 

@metlos could you please send request for taking part of the org ?

**Comment by metlos** [comment]
@mfrancisc I'm now a member of the openshift org.

**Pull request merged**
