### PR TITLE
Bug 1792105: Install imagestreams and templates on Z [4.2]

### PR DESCRIPTION
**Pull request by yselkowitz**
Backport of #222 for 4.2.

### CODE REVIEW

**Comment by gabemontero** [comment]
Perhaps conveying what I have tried to explain previously in the context of a PR will make this clearer.

This is *NOT* how we inject new samples into this operator as part of officially supporting the samples.

The teams providing the images tell us they are ready to support the changes when they update https://github.com/openshift/library accordingly.

We then pull the content from openshift/library into this repo.

You can see the start of this in
- https://projects.engineering.redhat.com/browse/RHELPLAN-28399
- https://github.com/sclorg/mariadb-container/pull/115
- https://github.com/openshift/library/pull/201

When the SCL team has done this for reasonable amount of content, I will then follow our process to make these changes.

We will not be merging this PR as is.

**Comment by yselkowitz** [comment]
We're not going to backport this all the way to 4.2 at this point.

**Pull request closed without merging**
