### PR TITLE
Remove deprecated tags 4.10

### PR DESCRIPTION
**Pull request by larsl-net**
Since the change of the RedHat Registry to digests V2 schema 2 manifests some tags of SamplesOperator are broken.
https://access.redhat.com/articles/6138332

This PR removes these tags for 4.10 because our registry backup solution currently tries to pull the broken tags as well which is no longer possible.

RedHat Case: 03301724

### CODE REVIEW

**Comment by fbm3307** [comment]
@larsl-net can you open this PR in current master..?

 First the PR gets merged in Master, and then they are backported to the previous branches

**Comment by larsl-net** [comment]
The current master Branch only contains Images with the old scheme version from `quay.io` wich are currently working.

Tags with schemVersion: 1 from `master`
```
quay.io/wildfly/wildfly-centos7:17.0
quay.io/wildfly/wildfly-centos7:18.0
quay.io/wildfly/wildfly-centos7:24.0
quay.io/wildfly/wildfly-centos7:25.0
quay.io/wildfly/wildfly-runtime-centos7:17.0
quay.io/wildfly/wildfly-runtime-centos7:18.0
quay.io/wildfly/wildfly-runtime-centos7:25.0
```

Simple script for finding `schemaVersion: 1` ImageStremTags from source
```bash
IMAGESTREAM_FILES="$(ls assets/operator/*/*/imagestreams/*)"

for file in $IMAGESTREAM_FILES; do
    for images in "$(jq -r '.spec.tags[] | select(.from.kind == "DockerImage") | .from.name' $file)"; do
        for image in $images; do
            if [ $(skopeo inspect --raw docker://$image | jq -r '.schemaVersion') == 1 ]; then
                echo "$image"
            fi
        done;
    done;
done;
```

I have also found some Jenkins images wich are no more exisitng on `registry.redhat.io`.

**Comment by fbm3307** [comment]
@larsl-net , i have reviewed the PR and tried finding the possible outcome of this, this PR is in release4-10 branch which is invalid i cannot merge it, also i see all the required tests failing on it.
The Problem you are facing about the schema version of  imagestreams, that cannot be removed/deleted from the Samples operator code, that changes needs to take place from Source of Imagestreams from where the Samples operator gets the imagestreams. To explain you better, Samples operator gets the tags and version of each imagestreams from it own repo and hence it is in hands of the Imagestreams owners to change it. 
The changes you made here in assets folder, they get reverted in every release , that cannot be the solution for your problem. 
Can you try using the latest imagestream tags..?? Meanwhile i shall try looking into the main code if i can somehow block the downloading of deprecated imagestream tags.

**Comment by larsl-net** [comment]
@fbm3307 the basic problem is that we have a harbor that clones the cluster registry. This fails with our newer clusters because of the old tags.

**Comment by fbm3307** [comment]
@larsl-net okay i understabd, can you try new tags..?

**Comment by larsl-net** [comment]
@fbm3307 Do you mean new tags from the ImageStreams or the Operator?
We can't restrict which tags are pulled from the cluster by our Habor.

Other tags from the operator can be tested.

**Comment by fbm3307** [comment]
@larsl-net 
the removal of old tags/version of imagestreams needs to happen at each individual imagestream repo, you can get the location of each repo from "https://github.com/openshift/library/blob/master/official.yaml". you can go and raise a PR in each repo of imagestreams where there are old tags/version.
Once the specific imagestream repo maintainers approve the PR, those changes will flow to Samples operator.
The current PR cannot go ahead , as the changes are required to happen at each imagestream repo level and then during sync samples operator will pick it up.
Please close this PR

**Pull request closed without merging**
