### PR TITLE
Bug 1993840: avoid immediate degraded on intermittent API errors; set reason/message when Available=false

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @dperaza4dustbit

### CODE REVIEW

**Review by dperaza4dustbit — APPROVED** [review]
lgtm

**Comment by gabemontero** [comment]
unrelated flakes, both ocp and okd

won't skip okd just yet

/retest

**Comment by gabemontero** [comment]
> lgtm

@dperaza4dustbit  - there has to be a '/' right before the lgtm for it to take effect

**Pull request merged**
