### PR TITLE
Bug 1872080: Sync RHEL/CentOS/UBI 8 imagestreams changes

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by gabemontero** [comment]
I'll wait for initial e2e results @yselkowitz before lgtm'ing

**Comment by yselkowitz** [comment]
Yes, of course.

**Comment by gabemontero** [comment]
e2e-aws  looks like unrelated flake hoopla at first blush

we also need the non-default jenkins run to go clean

/test e2e-aws-jenkins

if jenkins and image eco is clean I'll lgtm

**Comment by gabemontero** [comment]
OK jenkins passed ... that's good

image eco looks buggared:  https://prow.ci.openshift.org/log?container=test&id=1298603710456270849&job=pull-ci-openshift-cluster-samples-operator-master-e2e-aws-image-ecosystem

see if I can manually poke it 

/test e2e-aws-image-ecosystem

**Comment by gabemontero** [comment]
know unit test flake in new okd job

/test okd-unit

**Comment by gabemontero** [comment]
Looks like https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/317/pull-ci-openshift-cluster-samples-operator-master-e2e-aws-image-ecosystem/1298670500670607360 has some real errors @yselkowitz 

I have to step away for the rest of the day but can help triage tomorrow if need be.

**Comment by yselkowitz** [comment]
Found a typo which seems to explain the errors:
https://github.com/sclorg/s2i-nodejs-container/pull/253

Fixed that locally for now and retrying.

**Comment by gabemontero** [comment]
@yselkowitz there seems to be a problem with some jboss  imagestreams in okd

per https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/317/pull-ci-openshift-cluster-samples-operator-master-okd-e2e-aws-operator/1298715639766061056

     cluster_samples_operator_test.go:413: imagestreams.image.openshift.io "jboss-fuse70-console" not found
    cluster_samples_operator_test.go:413: imagestreams.image.openshift.io "jboss-fuse70-console" not found

     cluster_samples_operator_test.go:413: imagestreams.image.openshift.io "jboss-eap64-openshift" not found
    cluster_samples_operator_test.go:413: imagestreams.image.openshift.io "jboss-eap64-openshift" not found

unfortunately the must gather did not work in the test run

I'll dig more thoroughly tomorrow see if I can find some more indication of what is going on from the available data.

Otherwise, I may need to install okd and then override the samples operator with this PR to fully diagnose.

Let's pause on further retesting after these next three runs complete if they are still failing.

**Comment by yselkowitz** [comment]
There shouldn't be any such imagestreams in OKD at all, and I don't see where this is coming from or how this change would trigger that, so unless this was a fluke, I'll standby for your input.

Good news is with the one typo fix for nodejs, image eco passed.

**Comment by gabemontero** [comment]
> There shouldn't be any such imagestreams in OKD at all, and I don't see where this is coming from or how this change would trigger that, so unless this was a fluke, I'll standby for your input.

The problem is the operator e2e is hardwired for ocp content:  https://github.com/openshift/cluster-samples-operator/blob/master/test/e2e/cluster_samples_operator_test.go#L321

I'll see if I can sort that our this morning. If I get stuck in the weeds, we'll override / temporarily disable that new e2e for this PR.

the okd-e2e-aws job is normal non sample flakes 

let's give that the chance to get clean

/test okd-e2e-aws

> 
> Good news is with the one typo fix for nodejs, image eco passed.

cool

**Comment by yselkowitz** [comment]
okd-e2e-aws finally passed, just the one test left.

**Comment by gabemontero** [comment]
OK @yselkowitz I've got an env based toggle that allows okd-e2e-aws-operator to pass locally with an OKD cluster I provisioned this AM that deploys OKD content.

I just need to get the openshift/release prow sorted out so I can toggle in the e2e whether it is OKD or OCP

**Comment by gabemontero** [comment]
> /test okd-e2e-aws-operator

it is not quite ready yet @yselkowitz 

I'm watching https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/11340/rehearse-11340-pull-ci-openshift-cluster-samples-operator-master-okd-e2e-aws-operator/1299043612046135296 from https://github.com/openshift/release/pull/11340

if it passes we'll merge that PR and then you can retest that job here

**Comment by gabemontero** [comment]
my guess is @yselkowitz your current okd-e2e-aws-operator test run will fail, but then you can retest with https://github.com/openshift/release/pull/11340 now merged and you should have better luck

**Comment by gabemontero** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/317/pull-ci-openshift-cluster-samples-operator-master-okd-e2e-aws-operator/1299062296089202688 was still the old flavor of e2e ... didn't have the OKD evn var:

`KUBERNETES_CONFIG=/tmp/admin.kubeconfig go test -parallel 1 -timeout 30m -v ./test/e2e/...`

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/317/pull-ci-openshift-cluster-samples-operator-master-okd-e2e-aws-operator/1299089497840947200

was a ci flake:

```
2020/08/27 21:02:04 Ran for 41s
error: some steps failed:
  * could not initialize namespace: could not create role binding for: Timeout: request did not complete within allowed duration
time="2020-08-27T21:02:04Z" level=info msg="Reporting job state 'failed' with reason 'initializing_namespace'"
```

wait about 30 to 60 minutes to make sure the latest prow defs have been synced to the cluster

**Comment by yselkowitz** [comment]
It passed in the templates test PR, so let's try it again here:
/test okd-e2e-aws-operator

**Comment by yselkowitz** [comment]
all tests passed!

**Comment by yselkowitz** [comment]
e2e-aws passed before, why not now?

**Comment by adambkaplan** [comment]
/hold

Looks like the ruby imagestream is not found...

**Comment by adambkaplan** [comment]
In fact, looks like the only imagestreams installed are the ones that come from the CVO payload (cli, installer, must-gather, etc.)

**Comment by yselkowitz** [comment]
How did that happen, and how did image eco pass then?

**Comment by adambkaplan** [comment]
/cc @coreydaley @gabemontero 

Did the OKD work cause us to regress here?

**Comment by yselkowitz** [comment]
> Found a typo which seems to explain the errors: [sclorg/s2i-nodejs-container#253](https://github.com/sclorg/s2i-nodejs-container/pull/253)

FYI this has [merged into the library](https://github.com/openshift/library/commit/574e8c9c8ef24484cc25938e92d8ba78b9742002).

**Comment by gabemontero** [comment]
> /cc @coreydaley @gabemontero
> 
> Did the OKD work cause us to regress here?

No turns out registry.redhat.io was inaccessible during the last e2e-aws install, so as expected we boostrapped as removed.  From the sample operator pod logs:

```
2020-08-28T12:23:57.385716305Z time="2020-08-28T12:23:57Z" level=info msg="Go Version: go1.14.7"
2020-08-28T12:23:57.385824475Z time="2020-08-28T12:23:57Z" level=info msg="Go OS/Arch: linux/amd64"
2020-08-28T12:23:57.388943282Z time="2020-08-28T12:23:57Z" level=info msg="template client &v1.TemplateV1Client{restClient:(*rest.RESTClient)(0xc000378aa0)}"
2020-08-28T12:23:57.389031970Z time="2020-08-28T12:23:57Z" level=info msg="image client &v1.ImageV1Client{restClient:(*rest.RESTClient)(0xc000378b40)}"
2020-08-28T12:24:27.458707568Z time="2020-08-28T12:24:27Z" level=info msg="test connection to registry.redhat.io failed with dial tcp: lookup registry.redhat.io on 172.30.0.10:53: read udp 10.130.0.27:36367->172.30.0.10:53: read: connection refused"
2020-08-28T12:24:47.465315721Z time="2020-08-28T12:24:47Z" level=info msg="test connection to registry.redhat.io failed with dial tcp: lookup registry.redhat.io on 172.30.0.10:53: read udp 10.130.0.27:48563->172.30.0.10:53: i/o timeout"
2020-08-28T12:25:42.464536215Z time="2020-08-28T12:25:42Z" level=info msg="test connection to registry.redhat.io failed with dial tcp: lookup registry.redhat.io on 172.30.0.10:53: read udp 10.130.0.27:43893->172.30.0.10:53: i/o timeout"
2020-08-28T12:26:37.462511003Z time="2020-08-28T12:26:37Z" level=info msg="test connection to registry.redhat.io failed with dial tcp: lookup registry.redhat.io on 172.30.0.10:53: read udp 10.130.0.27:41725->172.30.0.10:53: i/o timeout"
2020-08-28T12:27:32.460467626Z time="2020-08-28T12:27:32Z" level=info msg="test connection to registry.redhat.io failed with dial tcp: lookup registry.redhat.io on 172.30.0.10:53: read udp 10.130.0.27:40758->172.30.0.10:53: i/o timeout"
2020-08-28T12:28:22.465200136Z time="2020-08-28T12:28:22Z" level=info msg="test connection to registry.redhat.io failed with dial tcp: lookup registry.redhat.io on 172.30.0.10:53: read udp 10.130.0.27:60010->172.30.0.10:53: i/o timeout"
2020-08-28T12:28:22.465200136Z time="2020-08-28T12:28:22Z" level=info msg="unable to establish HTTPS connection to registry.redhat.io after 3 minutes, bootstrap to Removed"
2020-08-28T12:28:22.465200136Z time="2020-08-28T12:28:22Z" level=info msg="creating default Config"
2020-08-28T12:28:25.526963661Z time="2020-08-28T12:28:25Z" level=info msg="waiting for informer caches to sync"
2020-08-28T12:28:25.632328859Z time="2020-08-28T12:28:25Z" level=info msg="started events processor"
2020-08-28T12:28:25.694692455Z time="2020-08-28T12:28:25Z" level=info msg="Attempting stage 1 Removed management state: RemovePending == true"
2020-08-28T12:28:25.694692455Z time="2020-08-28T12:28:25Z" level=info msg="CRDUPDATE process mgmt update spec Removed status "
2020-08-28T12:28:28.757571421Z time="2020-08-28T12:28:28Z" level=info msg="management state set to removed so deleting samples"
2020-08-28T12:28:28.775967909Z time="2020-08-28T12:28:28Z" level=info msg="Attempting stage 2 Removed management state: Status == Removed"
2020-08-28T12:28:28.775967909Z time="2020-08-28T12:28:28Z" level=info msg="CRDUPDATE process mgmt update spec Removed status Removed"
2020-08-28T12:28:31.824736405Z time="2020-08-28T12:28:31Z" level=info msg="Attempting stage 3 Removed management state: RemovePending == false"
2020-08-28T12:28:31.824736405Z time="2020-08-28T12:28:31Z" level=info msg="CRDUPDATE process mgmt update spec Removed status Removed"
2020-08-28T12:28:50.707915392Z W0828 12:28:50.701796      12 reflector.go:424] github.com/openshift/client-go/template/informers/externalversions/factory.go:101: watch of *v1.Template ended with: an error on the server ("unable to decode an event from the watch stream: stream error: stream ID 13; INTERNAL_ERROR") has prevented the request from succeeding
2020-08-28T12:29:12.237668134Z W0828 12:29:12.235987      12 reflector.go:424] github.com/openshift/client-go/image/informers/externalversions/factory.go:101: watch of *v1.ImageStream ended with: an error on the server ("unable to decode an event from the watch stream: stream error: stream ID 17; INTERNAL_ERROR") has prevented the request from succeeding
2020-08-28T12:29:31.003425914Z W0828 12:29:31.002859      12 reflector.go:424] github.com/openshift/client-go/template/informers/externalversions/factory.go:101: watch of *v1.Template ended with: an error on the server ("unable to decode an event from the watch stream: stream error: stream ID 63; INTERNAL_ERROR") has prevented the request from succeeding
```

Let's see how it looks now 

/retest

**Comment by gabemontero** [comment]
and its green again

/hold cancel

**Comment by gabemontero** [comment]
> @yselkowitz: The following test **failed**, say `/retest` to rerun all failed tests:
> Test name 	Commit 	Details 	Rerun command
> ci/prow/e2e-aws-operator 	[b9a5e1b](https://github.com/openshift/cluster-samples-operator/commit/b9a5e1bc15dcc8dec1968a4a3cf5a33786c9ccf3) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/317/pull-ci-openshift-cluster-samples-operator-master-e2e-aws-operator/1299736413629059072) 	`/test e2e-aws-operator`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openshift&repo=cluster-samples-operator&pr=317). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:yselkowitz).

network operator went degraded during install on this last run ... unrelated to this PR

/retest

**Pull request merged**
