### PR TITLE
Bug 1792102: Install imagestreams and templates on Power and Z [4.4]

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by gabemontero** [comment]
Perhaps conveying what I have tried to explain previously in the context of a PR will make this clearer.

This is *NOT* how we inject new samples into this operator as part of officially supporting the samples.

The teams providing the images tell us they are ready to support the changes when they update https://github.com/openshift/library accordingly.

We then pull the content from openshift/library into this repo.

You can see the start of this in
- https://projects.engineering.redhat.com/browse/RHELPLAN-28399
- https://github.com/sclorg/mariadb-container/pull/115
- https://github.com/openshift/library/pull/201

When the SCL team has done this for reasonable amount of content, I will then follow our process to make these changes.

We will not be merging this PR as is.

**Comment by yselkowitz** [comment]
We could add the same imagestreams to openshift/library, but in the short term they would be manually curated, and the exact same content as in this PR.  Furthermore, we need to get this fixed all the way down to 4.2 for Z (and quickly), and AFAICS the library is not generally synced in stable branches, so a manual import would apparently anyway be needed on the stable branches.

We can certainly treat integration into openshift/library as the next step, but we're working on borrowed time here.  Therefore, please remove the holds and allow us to proceed.

**Comment by gabemontero** [comment]
fyi openshift/library is synced automatically on a nightly basis

@bparees .... as I've stated in other channels, there is a disconnect between our org's view on priority of samples on s390/ppc and the multi-arch team's view.

Can you please work with @yselkowitz and the whoever else on the multi arch team is needed to get on a common page here.

If need be, we can prioritize our Jiras and SCL's Jiras to do this correctly.

Of if we want to allow this circumvention of how we do things, I would like the decision to come from the appropriate levels in our org vs. me making the decision in a vacuum.

@pweil- @adambkaplan @siamaksade FYI

**Comment by yselkowitz** [comment]
openshift/library is updated regularly, but that is not synced into cluster-samples-operator nearly as often, not automatically, and seemingly never in stable branches.

In master (4.4+), there was an update just a few days ago.
In 4.3, the last update was on 31 October.
In 4.2, the last update was on 16 July.

So it seems that the policy to not update imagestreams and templates in stable branches continues to this day.  Therefore, it would seem that a manual import just for P&Z would anyway be necessary, so as to not disrupt x86.  Since anything being fixed in a stable branch must first be fixed in master, I see no viable alternative to the approach taken here.  While we're open to suggestions, we need this fixed now, not at an indeterminate time in the future.

**Comment by gabemontero** [comment]
> openshift/library is updated regularly, but that is not synced into cluster-samples-operator nearly as often, not automatically, and seemingly never in stable branches.
> 
> In master (4.4+), there was an update just a few days ago.
> In 4.3, the last update was on 31 October.
> In 4.2, the last update was on 16 July.

Syncing from openshift/libray to this repo is the type of PR we would accept.

See https://github.com/openshift/cluster-samples-operator#update-the-content-in-this-repository-from-httpsgithubcomopenshiftlibrary

> 
> So it seems that the policy to not update imagestreams and templates in stable branches continues to this day. Therefore, it would seem that a manual import just for P&Z would anyway be necessary, so as to not disrupt x86. Since anything being fixed in a stable branch must first be fixed in master, I see no viable alternative to the approach taken here. While we're open to suggestions, we need this fixed now, not at an indeterminate time in the future.

**Comment by gabemontero** [comment]
> openshift/library is updated regularly, but that is not synced into cluster-samples-operator nearly as often, not automatically, and seemingly never in stable branches.
> 
> In master (4.4+), there was an update just a few days ago.
> In 4.3, the last update was on 31 October.
> In 4.2, the last update was on 16 July.
> 
> So it seems that the policy to not update imagestreams and templates in stable branches continues to this day. Therefore, it would seem that a manual import just for P&Z would anyway be necessary, so as to not disrupt x86. Since anything being fixed in a stable branch must first be fixed in master, I see no viable alternative to the approach taken here. While we're open to suggestions, we need this fixed now, not at an indeterminate time in the future.

You convince @bparees and my management that you why you need this now, with no other temporary workaround, we'll go from there.

**Comment by bparees** [comment]
@yselkowitz While I'm happy to hear of customer interest/desire for the content the samples operator provides, on additional architectures, I have a couple questions/concerns before we do this:

1) Has the SCL team signed off on these imagestreams?  Have they agreed to support these images on these architectures if/when issues occur?  Part of the benefit of us getting content from openshift/library is that we are pulling content that the teams that own the images have contributed, which implies they believe it works/has been tested/etc.  If we create our own imagestreams pointing to other team's images, those teams are likely to be caught off guard by bugs that openshift customers hit when using the imagestreams.

What efforts have been made to get the SCL team to contribute this content into openshift/library and why have they failed?  To what extent have these images themselves been tested on the various architectures (beyond just confirming the imagestream imports successfully?)

2) A relative nit, but: how do we make sure future runs of the samples import script don't stomp these changes?  (@gabemontero probably knows best what the samples-operator import script does and whether or not that is problem here)

3) we have no non-x86 CI on this repo.  How do we ensure future changes don't break samples operator functionality on non-x86 platforms?  (How do we even know the changes in this PR are correct?  These changes aren't aligned w/ the changes @gabemontero prototyped elsewhere: https://github.com/gabemontero/cluster-samples-operator/commit/8f396043ac99dc8e68f251eb363141b42c5f830e )

4) Past discussions of enabling additional architectures for the samples-operator included discussions about how admins can choose + switch the architecture they want installed (or how we prevent them from changing it).  We punted on all those discussions when we simplified to only supporting x86.  Since this PR is reintroducing support for additional architectures, how are those scenarios handled?  And how will heterogeneous clusters be handled, given the answers to those questions?  Are we comfortable w/ the behavior we are implementing here?

If there is a critical need to get something into a customer's hands immediately, such that we can't afford the time to resolve the items i listed, then I think we need to see the customer cases and escalation(internal email please) so the right people(Multiarch leadership, SCL leadership, Openshift leadership) can make an informed decision about whether circumventing that design process is necessary/justified.  After all, there are certainly other ways to get samples into a customer's hands in the short term.  Similarly if this is needed for internal testing purposes, test cases can be written to install the imagestreams as part of the test.

**Comment by bparees** [comment]
```
In master (4.4+), there was an update just a few days ago.
In 4.3, the last update was on 31 October.
In 4.2, the last update was on 16 July.
```



So it seems that the policy to not update imagestreams and templates in stable branches continues to this day. 
```

Correct, we don't generally update the imagestream/template content on z-stream releases unless we are fixing a bug in the content.  That same rule/logic would apply to the introduction of new content (such as imagestreams for new architectures).

```
Therefore, it would seem that a manual import just for P&Z would anyway be necessary, so as to not disrupt x86.
```

If we're talking about updating a z-stream branch, yes.  But again then i'd question why we're introducing new content (z, ppc) on a z-stream which is generally not something we do in z-streams.

```
 Since anything being fixed in a stable branch must first be fixed in master, I see no viable alternative to the approach taken here. While we're open to suggestions, we need this fixed now, not at an indeterminate time in the future.
```

this isn't "fixing" something, it's introducing a new feature.  I need a better understanding of the reason behind the urgency and why workarounds(manual installation of imagestreams/templates) are not viable while we take the time to do this with proper sign offs from the teams being directly and indirectly impacted (namely SCL)

**Comment by gabemontero** [comment]
FYI https://projects.engineering.redhat.com/browse/RHELPLAN-28399 is the request I registered with SCL last October to submit imagestreams for their images on non x86 architectures

**Comment by yselkowitz** [comment]
This PR has been modified to include the results of the sync script for ppc64le and s390x once https://github.com/openshift/library/pull/205 has been merged, per your request to add the imagestreams in this fashion.

**Comment by yselkowitz** [comment]
>     1. Has the SCL team signed off on these imagestreams?  Have they agreed to support these images on these architectures if/when issues occur?  Part of the benefit of us getting content from openshift/library is that we are pulling content that the teams that own the images have contributed, which implies they believe it works/has been tested/etc.  If we create our own imagestreams pointing to other team's images, those teams are likely to be caught off guard by bugs that openshift customers hit when using the imagestreams.  To what extent have these images themselves been tested on the various architectures (beyond just confirming the imagestream imports successfully?)

These images have been available for these architectures for a long time already, and imagestreams for these images were included in OCP 3.10 and 3.11 for Power, so there are no surprises here.

>     2. A relative nit, but: how do we make sure future runs of the samples import script don't stomp these changes?  (@gabemontero probably knows best what the samples-operator import script does and whether or not that is problem here)

The PR includes the necessary changes to the import script to pull in future changes for ppc64le and s390x as well.
 
>     3. we have no non-x86 CI on this repo.  How do we ensure future changes don't break samples operator functionality on non-x86 platforms?  (How do we even know the changes in this PR are correct?  These changes aren't aligned w/ the changes @gabemontero prototyped elsewhere: [gabemontero@8f39604](https://github.com/gabemontero/cluster-samples-operator/commit/8f396043ac99dc8e68f251eb363141b42c5f830e) )

We have already tested a build with these changes included, and it worked as expected.

>     4. Past discussions of enabling additional architectures for the samples-operator included discussions about how admins can choose + switch the architecture they want installed (or how we prevent them from changing it).  We punted on all those discussions when we simplified to only supporting x86.  Since this PR is reintroducing support for additional architectures, how are those scenarios handled?  And how will heterogeneous clusters be handled, given the answers to those questions?  Are we comfortable w/ the behavior we are implementing here?

Heterogeneous clusters are not yet supported, and would likely take extensive work well beyond the scope of this operator.  Having no idea yet exactly what that will end up looking like, it's really too early to plan for that at this point.

> If there is a critical need to get something into a customer's hands immediately, such that we can't afford the time to resolve the items i listed, then I think we need to see the customer cases and escalation(internal email please) so the right people(Multiarch leadership, SCL leadership, Openshift leadership) can make an informed decision about whether circumventing that design process is necessary/justified. After all, there are certainly other ways to get samples into a customer's hands in the short term. Similarly if this is needed for internal testing purposes, test cases can be written to install the imagestreams as part of the test.

There is nothing left to resolve except for merging these PRs.

**Comment by yselkowitz** [comment]
> Correct, we don't generally update the imagestream/template content on z-stream releases unless we are fixing a bug in the content. That same rule/logic would apply to the introduction of new content (such as imagestreams for new architectures).

In this case, the bug is that the content is completely missing.  The stable branch PRs do not touch the x86 imagestreams for this reason, and the minor code change to unhobble the operator clearly only affects non-x86 architectures.

> If we're talking about updating a z-stream branch, yes. But again then i'd question why we're introducing new content (z, ppc) on a z-stream which is generally not something we do in z-streams.

Because the operator is not fully functional without it.

> this isn't "fixing" something, it's introducing a new feature. I need a better understanding of the reason behind the urgency and why workarounds(manual installation of imagestreams/templates) are not viable while we take the time to do this with proper sign offs from the teams being directly and indirectly impacted (namely SCL)

This is not a new feature, it is fixing an existing feature to work on Power and Z ("feature parity"), and all such work is being accepted into stable branches.

**Comment by yselkowitz** [comment]
Closing in order to file from a different branch.

**Pull request closed without merging**
