### PR TITLE
Bug 1990988: Refreshing samples for OCP 4.9

### PR DESCRIPTION
**Pull request by dperaza4dustbit**
Ran the library synch and sending the changes that resulted. Preliminary investigation looks good and script output looks like it did its job.

### CODE REVIEW

**Comment by vrutkovs** [comment]
This breaks OKD

```
fail [github.com/openshift/origin/test/extended/templates/templateinstance_readiness.go:107]: Unexpected error:
    <*errors.errorString | 0xc002068780>: {
        s: "Failed to import expected imagestreams, latest error status: ImageStream Error: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, ListMeta:v1.ListMeta{SelfLink:\"\", ResourceVersion:\"\", Continue:\"\", RemainingItemCount:(*int64)(nil)}, Status:\"Failure\", Message:\"imagestreams.image.openshift.io \\\"mongodb\\\" not found\", Reason:\"NotFound\", Details:(*v1.StatusDetails)(0xc000efa9c0), Code:404}} \n",
    }
    Failed to import expected imagestreams, latest error status: ImageStream Error: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"imagestreams.image.openshift.io \"mongodb\" not found", Reason:"NotFound", Details:(*v1.StatusDetails)(0xc000efa9c0), Code:404}} 
    
occurred
```

**Comment by gabemontero** [comment]
> This [breaks](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-okd-4.8-e2e-aws/1426090871937306624) OKD
> 
> ```
> fail [github.com/openshift/origin/test/extended/templates/templateinstance_readiness.go:107]: Unexpected error:
>     <*errors.errorString | 0xc002068780>: {
>         s: "Failed to import expected imagestreams, latest error status: ImageStream Error: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, ListMeta:v1.ListMeta{SelfLink:\"\", ResourceVersion:\"\", Continue:\"\", RemainingItemCount:(*int64)(nil)}, Status:\"Failure\", Message:\"imagestreams.image.openshift.io \\\"mongodb\\\" not found\", Reason:\"NotFound\", Details:(*v1.StatusDetails)(0xc000efa9c0), Code:404}} \n",
>     }
>     Failed to import expected imagestreams, latest error status: ImageStream Error: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"imagestreams.image.openshift.io \"mongodb\" not found", Reason:"NotFound", Details:(*v1.StatusDetails)(0xc000efa9c0), Code:404}} 
>     
> occurred
> ```

I'm a little confused @vrutkovs  .... mongodb is not one of the imagestreams listed at https://github.com/openshift/origin/blob/c5feec4ee991a031fc6700f3d8c6083e1ef2c48b/test/extended/util/framework.go#L245

where that is the method called at https://github.com/openshift/origin/blob/master/test/extended/templates/templateinstance_readiness.go#L106

and yes, mongodb is gone from both OKD and OCP cause of the licensing hoopla with them.

Could you point us to whatever CI job this came from so we can look at must gather ?

**Comment by vrutkovs** [comment]
Seems cluster-samples-operator is using 4.8 tests still - could you LGTM https://github.com/openshift/release/pull/20055 so that it would use 4.9 on master?

**Comment by gabemontero** [comment]
> Seems cluster-samples-operator is using 4.8 tests still - could you LGTM [openshift/release#20055](https://github.com/openshift/release/pull/20055) so that it would use 4.9 on master?

ahh ... that explains it ....forgot about that correlation

lgtm posted thanks @vrutkovs

**Pull request merged**
