### PR TITLE
Bug 1881573: remove imminent SCL EOL images

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @yselkowitz 

I've verified that associated templates refer to later tags (per recent changes from @yselkowitz )

Also note, a couple of the imagestreams for s390x and ppc64le already had these EOL images removed.

If OKD is still broke (per last update from @vrutkovs ) will override

@crawford FYI

@adambkaplan @coreydaley-redhat FYI we've been officially asked by the powers that be to pull this into 4.6.0

### CODE REVIEW

**Comment by yselkowitz** [comment]
https://github.com/openshift/library/commit/13e843882f6972c426de5db67b4e27563e58db19 removes the mention of 3.6-ubi7 removed here (by moving to 3.8-ubi*), would that fall under this exception?

**Comment by gabemontero** [comment]
> [openshift/library@13e8438](https://github.com/openshift/library/commit/13e843882f6972c426de5db67b4e27563e58db19) removes the mention of 3.6-ubi7 removed here (by moving to 3.8-ubi*), would that fall under this exception?

sure pushed as a separate commit; let's see how it looked

3.6-ubi8 passed image eco

**Comment by gabemontero** [comment]
bad install operator

/test e2e-aws-operator

**Comment by gabemontero** [comment]
uh oh ... the latest e2e-aws failure is related to these changes:

```
The ImageStreamTag "php:7.2" is invalid: from: Error resolving ImageStreamTag php:7.2 in namespace openshift: unable to find latest tagged image
```

Need to find whatever template is using that.

**Comment by gabemontero** [comment]
https://github.com/openshift/origin/pull/25539 will need to merge before this can

**Comment by gabemontero** [comment]
ah ... okd is more healthy now ... some passing e2e's ... okd-e2e-aws has the same php:7.2 issue in openshift/origin

**Comment by yselkowitz** [comment]
Also missing from here is the sync of the postgresql imagestreams for ppc64le and s390x.  Can I suggest resetting and redoing this PR with the following steps (provided nothing significant changes in the library by the time you see this):
```
./library-sync.sh
git reset
git checkout assets/operator/ocp-s390x/webserver/ assets/operator/ocp-x86_64/{rhdm,rhpam,webserver} assets/operator/ocp-{ppc64le,s390x,x86_64}/mongodb/templates assets/operator/okd-x86_64/mongodb/templates
git add assets/
git commit
```

**Comment by gabemontero** [comment]
> Also missing from here is the sync of the postgresql imagestreams for ppc64le and s390x. Can I suggest resetting and redoing this PR with the following steps (provided nothing significant changes in the library by the time you see this):
> 
> ```
> ./library-sync.sh
> git reset
> git checkout assets/operator/ocp-s390x/webserver/ assets/operator/ocp-x86_64/{rhdm,rhpam,webserver} assets/operator/ocp-{ppc64le,s390x,x86_64}/mongodb/templates assets/operator/okd-x86_64/mongodb/templates
> git add assets/
> git commit
> ```

is that postgresql sync related to EOL images?

**Comment by gabemontero** [comment]
> > Also missing from here is the sync of the postgresql imagestreams for ppc64le and s390x. Can I suggest resetting and redoing this PR with the following steps (provided nothing significant changes in the library by the time you see this):
> > ```
> > ./library-sync.sh
> > git reset
> > git checkout assets/operator/ocp-s390x/webserver/ assets/operator/ocp-x86_64/{rhdm,rhpam,webserver} assets/operator/ocp-{ppc64le,s390x,x86_64}/mongodb/templates assets/operator/okd-x86_64/mongodb/templates
> > git add assets/
> > git commit
> > ```
> 
> is that postgresql sync related to EOL images?
> 
> I've done the above and am looking at the diffs now.

pushed as separate commit @yselkowitz

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Comment by gabemontero** [comment]
the image eco mariadb failure looks to be env related (a pretest request for nodes failed) ... given image-eco passed previously, and the latest commit did not touch mariadb, reasonably confident we'll be OK here

we'll still need to retest e2e-aws, e2e-aws-builds, once https://github.com/openshift/origin/pull/25539 lands  

/test e2e-aws-image-ecosystem

**Comment by gabemontero** [comment]
/hold

until openshift/origin updates merge

**Comment by gabemontero** [comment]
https://github.com/openshift/origin/pull/25539 has landed

/hold cancel

/test e2e-aws-builds

**Comment by gabemontero** [comment]
Though the tests are still running, I was able to log into the build cluster and verify that we have passing build prune tests again in e2e-aws, e2e-aws-builds, etc.

**Comment by gabemontero** [comment]
/hold

in case there is some issue with the openshift/origin test change getting propagated ... will un-hold when I see green tests

**Comment by gabemontero** [comment]
/retest

(all php:7.2 related / started last run too early hopefully)

**Comment by yselkowitz** [comment]
just 2 okd failures now

**Comment by gabemontero** [comment]
I think the okd promotions are slower ... those last 2 failures still had php:7.2 meaning older openshift/origin

one more time ... otherwise will override.... the passing in ocp versions is sufficient

/retest

**Pull request merged**
