### PR TITLE
Bug 2027745: Move openshift build-machinery-go dependency

### PR DESCRIPTION
**Pull request by dperaza4dustbit**
Need to move dependencies for OCP 4.10

### CODE REVIEW

**Comment by gabemontero** [comment]
need a bz associated to merge

/retitle Bug 2027745: Move openshift build-machinery-go dependency

**Comment by gabemontero** [comment]
looks like CI's image registry is down ... think everything will fail until that is resolved

**Comment by gabemontero** [comment]
ok the make bump may have broken something

can you try a make build locally in your PR branch @dperaza4dustbit ?

**Comment by gabemontero** [comment]
@dperaza4dustbit see https://github.com/openshift/cluster-samples-operator/pull/363#issue-845161434

you need to run `make update` and commit the changes

you can run `make verify` locally for confirm things are now happy

**Comment by gabemontero** [comment]
per https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/407/pull-ci-openshift-cluster-samples-operator-master-verify/1481242829228347392/build-log.txt the ibm cloud managed yaml needs to be updated

**Comment by dperaza4dustbit** [comment]
@gabemontero I was missing some vendors file that I did not push, fixed and updated here. That explains how it build locally but not on CI

**Comment by gabemontero** [comment]
> @gabemontero I was missing some vendors file that I did not push, fixed and updated here. That explains how it build locally but not on CI

@dperaza4dustbit the verify failure https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/407/pull-ci-openshift-cluster-samples-operator-master-verify/1482047856306032640 since your last commit would imply that you did not run `make update`

is that the case?  if so let's discuss in slack, otherwise, do so and store the changes as a separate commit in this PR

**Comment by dperaza4dustbit** [comment]
> > @gabemontero I was missing some vendors file that I did not push, fixed and updated here. That explains how it build locally but not on CI
> 
> @dperaza4dustbit the verify failure https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/407/pull-ci-openshift-cluster-samples-operator-master-verify/1482047856306032640 since your last commit would imply that you did not run `make update`
> 
> is that the case? if so let's discuss in slack, otherwise, do so and store the changes as a separate commit in this PR

I did not, but when I did there was only this diff: 

dperaza@dperaza-mac cluster-samples-operator % git diff manifests/06-operator-ibm-cloud-managed.yaml
diff --git a/manifests/06-operator-ibm-cloud-managed.yaml b/manifests/06-operator-ibm-cloud-managed.yaml
index fcdc9380..8195d8a1 100644
--- a/manifests/06-operator-ibm-cloud-managed.yaml
+++ b/manifests/06-operator-ibm-cloud-managed.yaml
@@ -1,3 +1,4 @@
+# *** AUTOMATICALLY GENERATED FILE - DO NOT EDIT ***
 apiVersion: apps/v1
 kind: Deployment
 metadata:

Not sure how that will change anything but updated the PR to include this chance, on my local environment build and unit-test work as expected. We can connect on slack if this pass does not work.

**Comment by gabemontero** [comment]
> > > @gabemontero I was missing some vendors file that I did not push, fixed and updated here. That explains how it build locally but not on CI
> > 
> > 
> > @dperaza4dustbit the verify failure https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/407/pull-ci-openshift-cluster-samples-operator-master-verify/1482047856306032640 since your last commit would imply that you did not run `make update`
> > is that the case? if so let's discuss in slack, otherwise, do so and store the changes as a separate commit in this PR
> 
> I did not, but when I did there was only this diff:
> 
> dperaza@dperaza-mac cluster-samples-operator % git diff manifests/06-operator-ibm-cloud-managed.yaml diff --git a/manifests/06-operator-ibm-cloud-managed.yaml b/manifests/06-operator-ibm-cloud-managed.yaml index fcdc9380..8195d8a1 100644 --- a/manifests/06-operator-ibm-cloud-managed.yaml +++ b/manifests/06-operator-ibm-cloud-managed.yaml @@ -1,3 +1,4 @@ +# *** AUTOMATICALLY GENERATED FILE - DO NOT EDIT *** apiVersion: apps/v1 kind: Deployment metadata:
> 
> Not sure how that will change anything but updated the PR to include this chance, on my local environment build and unit-test work as expected. We can connect on slack if this pass does not work.

yep is what was needed for the verify job to pass

now down to unrelated flakes

/skip

**Pull request merged**
