### PR TITLE
Bug 1811143: purge removed imagestreams as a part of upgrade from progessing/impor…

### PR DESCRIPTION
**Pull request by gabemontero**
…terrors

from @vrutkovs 's 4.3.5 upgrade testing today

@openshift/openshift-team-developer-experience FYI

See bugzilla for analysis ... I believe hitting this is low.

@adambkaplan or @bparees ... preferences on who wants to be assigned ?

### CODE REVIEW

**Comment by gabemontero** [comment]
> /lgtm
> 
> @gabemontero per your analysis in the BZ, I'm inclined to agree that users will only hit this bug if
> 
>     1. They install a cluster
> 
>     2. They immediately upgrade to the next 4.y release
> 
>     3. Imagestream imports don't complete before the upgrade commences.

cool deal thanks @adambkaplan

**Comment by gabemontero** [comment]
the build pod for `hot deploy for openshift perl image` in image-eco never got out of pod initializing with container conditions like:

```
   - lastProbeTime: null
      lastTransitionTime: "2020-03-06T19:54:15Z"
      message: 'containers with incomplete status: [git-clone manage-dockerfile]'
      reason: ContainersNotInitialized
      status: "False"
      type: Initialized
```

no useful events in the debug about why that might happen.

/test e2e-aws-image-ecosystem

**Comment by vrutkovs** [comment]
/hold

e2e tests are failing for several times in a row. Lets see if clearing the namespace helps

**Comment by gabemontero** [comment]
namespaces cleared (or at least I can't see them):

```
gmontero ~ $ oc projects 
You have access to the following projects and can switch between them with 'oc project <projectname>':

ci - OpenShift CI
ci-stg
coreos
fcos
ocp
ocp-ppc64le
ocp-s390x
origin
origin-web-console - OpenShift Web Console Development
release-controller-test-release
gmontero ~ $ 
```

/hold cancel

/retest

**Comment by gabemontero** [comment]
I'll check before I go to bed, see if it is still spinning

**Pull request merged**
