### PR TITLE
[release-4.12] OCPBUGS-10918: update Jenkins to v4.12

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by gabemontero** [comment]
/approve
/lgtm
/hold 

let's unhold after the e2e-aws-jenkins passes

**Comment by gabemontero** [comment]
install flake

/test e2e-aws-jenkins

**Comment by fbm3307** [comment]
@coreydaley is this related to a CVE..? if yes please add the bug and CVE link here for us to review..?

**Comment by fbm3307** [comment]
@coreydaley since we have stopped accepting new tags or any updates starting ocp4.13 to the imagestreams/templates unless its a CVE or customer affecting bug, Please do give CVE/Bug number in this PR.

**Comment by coreydaley** [comment]
@fbm3307 Here is a list of CVE related bugs that are fixed in this version:

OCPBUGS-335
OCPBUGS-331
OCPBUGS-333
OCPBUGS-325
OCPBUGS-327
OCPBUGS-315
OCPBUGS-4440
OCPBUGS-6649
OCPBUGS-4060
OCPBUGS-3486
OCPBUGS-2549
OCPBUGS-2550
OCPBUGS-2703
OCPBUGS-2685
OCPBUGS-2715
OCPBUGS-2667
OCPBUGS-2673
OCPBUGS-2679
OCPBUGS-489
OCPBUGS-2709
OCPBUGS-2725
OCPBUGS-2691
OCPBUGS-905
OCPBUGS-914
OCPBUGS-329
OCPBUGS-323
OCPBUGS-1195
OCPBUGS-1095
OCPBUGS-1185
OCPBUGS-2697

**Comment by fbm3307** [comment]
@coreydaley Plz add ocpbug number to the title for this PR to merge.

**Comment by fbm3307** [comment]
@coreydaley please check the jira issue you mentioned here, looks like it is complaining for validity.

**Pull request merged**
