### PR TITLE
Bug 2107521: Remove EAP deprecated images from Samples Operator OCP release 4.10

### PR DESCRIPTION
**Pull request by fbm3307**
Remove EAP deprecated images from Samples Operator OCP release 4.10

Signed-off-by: Feny Mehta <fbm3307@gmail.com>

### CODE REVIEW

**Comment by jmesnil** [comment]
@fbm3307 theses 3 images for EAP are all deprecated and no longer maintained.

Could we simply delete the imagestream files? If we do so, would we remove them from 4.10 upgrades?
Otherwise, should we keep the imagestream and remove *all* tags (including `latest`)?

**Comment by fbm3307** [comment]
> @fbm3307 theses 3 images for EAP are all deprecated and no longer maintained.
> 
> Could we simply delete the imagestream files? If we do so, would we remove them from 4.10 upgrades? Otherwise, should we keep the imagestream and remove _all_ tags (including `latest`)?

@jmesnil these are not maintained for 4.10.x also.? if not maintained, i can modify this PR to delete these jsons.?

**Comment by jmesnil** [comment]
> > @fbm3307 theses 3 images for EAP are all deprecated and no longer maintained.
> > Could we simply delete the imagestream files? If we do so, would we remove them from 4.10 upgrades? Otherwise, should we keep the imagestream and remove _all_ tags (including `latest`)?
> 
> @jmesnil these are not maintained for 4.10.x also.? if not maintained, i can modify this PR to delete these jsons.?

Actually, I think your PR is correct. Let's remove the oldest non-v2 images only. This will be less disruptive for the users of older OCP releases as these imagestreams with the most recent images will still be present.
Finding a way to notify users that the images are unsupported is out of scope of this issue.

thanks!

**Comment by fbm3307** [comment]
The 3 test not passing are for OKD.
/lgtm

**Comment by fbm3307** [comment]
Closing this as not required anymore

**Pull request closed without merging**
