### PR TITLE
Remove single node prod cluster profile annotation as it is not used

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@dhellmann please confirm we don't need this

**Comment by dhellmann** [comment]
We do not need that annotation.

/lgtm

**Comment by bparees** [comment]
@gabemontero @dperaza4dustbit heads up, looks like a couple broken jobs on this repo.

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/405/pull-ci-openshift-cluster-samples-operator-master-okd-e2e-aws-image-ecosystem/1467864421723279360 is failing probably because the .NET SCL image was changed recently to *not* print the usage on default run.  I think it's safe to just disable that particular test.  (The .NET team talked to use before changing the behavior).

it's less obvious what went wrong here:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/405/pull-ci-openshift-cluster-samples-operator-master-okd-e2e-aws-builds/1467864421677142016

other than the obvious (we didn't get the oom killed message we expected.  I can see in the build pod that is dumped in the stdout for the test that we did get an exit code 137:


```
Containers:
  sti-build:
    Args:
      openshift-sti-build
      --loglevel=5
    State:      Terminated
      Reason:   Error
      Exit Code:    137
      Started:      Mon, 06 Dec 2021 15:19:27 +0000
      Finished:     Mon, 06 Dec 2021 15:19:40 +0000
 ```
 
 so perhaps something in okd is not translating the exit code correctly into the pod/build status.
 
 but it's certainly not related to this PR.

**Comment by bparees** [comment]
overriding valid-bz label for this trivial change

**Pull request merged**
