### PR TITLE
Bug 1805250: manifests: add openshift/oauth-proxy:v4.4 image

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
```

level=fatal msg="failed to initialize the cluster: Could not update imagestream \"openshift/oauth-proxy\" (228 of 433): the object is invalid, possibly due to local cluster configuration" | level=fatal msg="failed to initialize the cluster: Could not update imagestream \"openshift/oauth-proxy\" (228 of 433): the object is invalid, possibly due to local cluster configuration"
-- | --
level=fatal msg="failed to initialize the cluster: Could not update imagestream \"openshift/oauth-proxy\" (228 of 433): the object is invalid, possibly due to local cluster configuration"
 


```

**Comment by gabemontero** [comment]
/hold 

e2e-aws-builds is going to fail until https://github.com/openshift/origin/pull/24775 and can then be cherrypicked back to 4.2 ... details as to why in PR / associated bugzilla

**Comment by gabemontero** [comment]
https://github.com/openshift/origin/pull/24783 has merged - let's try e2e-aws-builds again

/hold cancel

/retest

**Comment by gabemontero** [comment]
/hold 

sorry, this is 4.2, not 4.4

**Comment by bparees** [comment]
https://github.com/openshift/origin/pull/24785 should merge shortly

/hold cancel

**Pull request merged**
