### PR TITLE
OCPBUGS-3426: Update Cluster Sample Operator dependencies and libraries for OCP 4.12

### PR DESCRIPTION
**Pull request by fbm3307**
Synching the libraries and updating Samples operator for OCP 4.12 release

Signed-off-by: Feny Mehta <fbm3307@gmail.com>

### CODE REVIEW

**Comment by yselkowitz** [comment]
One problem seems to be https://github.com/nodeshift-starters/nodejs-rest-http-crud/pull/351; can you manually un-delete the nodejs-postgresql-* files for all arches and try again while we sort that out with them?

**Comment by helio-frota** [comment]
Thanks for the retest, I'm seeing some failures but I have no idea if that still a problem with nodejs-rest-http-crud example. Please let me know and I can try to make changes ASAP to avoid to block your CI.

**Comment by fbm3307** [comment]
> Thanks for the retest, I'm seeing some failures but I have no idea if that still a problem with nodejs-rest-http-crud example. Please let me know and I can try to make changes ASAP to avoid to block your CI.

Thanks @helio-frota @yselkowitz for this prompt action, but i see that test still failing, and i am investing  its cause

**Comment by yselkowitz** [comment]
@fbm3307 you'll need to resync the samples, squash, and force push to see different results

**Comment by yselkowitz** [comment]
Progress, now we need https://github.com/nodeshift-starters/nodejs-rest-http-crud/pull/395

**Comment by helio-frota** [comment]
@yselkowitz merged thanks :+1:

**Comment by yselkowitz** [comment]
RHEL image-eco passed, looks like OKD image-eco has been broken for a while.
/lgtm
/assign @dperaza4dustbit

**Review by dperaza4dustbit — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
