### PR TITLE
Bug 1835995: ensure s390/ppc64le platforms bootstrap as removed following upgrade

### PR DESCRIPTION
**Pull request by gabemontero**
manual pick after cherrybot failure https://github.com/openshift/cluster-samples-operator/pull/277#issuecomment-635407445

### CODE REVIEW

**Comment by gabemontero** [comment]
Ah our old friend `forbidden: unable to validate against any security context constraint: []` on the image-eco failure.

I believe @soltysh has cherrypicks for the fix in progress via https://bugzilla.redhat.com/show_bug.cgi?id=1829327 ... I see that 4.4.z BZ is in POST, with one PR merged, but the other https://github.com/openshift/cluster-policy-controller/pull/25 still on HOLD.

Any chance on that getting its hold cancelled soon @soltysh ?

Sometimes the image-eco runs are able to avoid the issue if timing is right ... we'll see how lucky we are this week.

@mfojtik FYI

/retest

**Comment by gabemontero** [comment]
failed to acquire lease

/retest

**Comment by soltysh** [comment]
> Any chance on that getting its hold cancelled soon @soltysh ?

I'm waiting for e2e to pass, just re-triggered and dropped the hold, need to wait for tests to pass.

**Comment by soltysh** [comment]
@gabemontero you should be able to lgtm that other, it's waiting :)

**Pull request merged**
