### PR TITLE
Bug 2109036:Remove deprecated JWS images from Samples Operator OCP …

### PR DESCRIPTION
**Pull request by bekionel**
…release 4.9

### CODE REVIEW

**Comment by fbm3307** [comment]
Hi @bekionel this PR is no longer needed. Can you please close the PR.?
While weighing the amount of work to merge this PR , there is very little benefit from it, hence it is wise that we take another route to remove the deprecated imagestreams.

**Comment by bekionel** [comment]
Hi @fbm3307 , sure I will go ahead and close it. Should I also close the linked bugzilla that I had to create as well? Thanks!

**Comment by bekionel** [comment]
My mistake, I hadn't noticed the BZ had been closed, thanks @fbm3307

**Pull request closed without merging**
