### PR TITLE
simplify imagestream/template directory structure; more sensible dir name

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by gabemontero** [comment]
/hold

after verifying successful imagestream/template install with this change via the existing e2e's and associated must gather data, I'm going to push a preliminary openshift/library bump with the new dir structure to validate ... I'll ultimately drop the commit for now (we still have a bit more time before dcut and we know more changes are coming for 4.6)

**Comment by gabemontero** [comment]
ok dir change looks good .... now gonna try a (temporary) samples bump

**Comment by gabemontero** [comment]
image eco failure was the known cakephp mysql imagestream/template disconnect I always have to patch

**Comment by gabemontero** [comment]
samples operator upgraded fine in e2e-aws-upgrade failure ... some k8s level ones did not

**Comment by gabemontero** [comment]
ok .... test import looks fine ... dropping / getting ready for merge

**Comment by gabemontero** [comment]
@bparees your directory rename

**Comment by bparees** [comment]
love it.

/lgtm

/hold
(unhold at your leisure, wasn't sure if you had any other testing you wanted to do)

**Comment by gabemontero** [comment]
cool 

and nope, testing is done re: prior comments here

/hold cancel

**Pull request merged**
