### PR TITLE
Bump k8s 1.16.2

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @adambkaplan 
/assign @dmage 

@openshift/openshift-team-developer-experience fyi

### CODE REVIEW

**Comment by gabemontero** [comment]
Hmm ... CI image registry may be unhealthy:

`error: unable to parse image registry.svc.ci.openshift.org/ci-op-3cmwb3xd/stable@sha256:8a154e2401cbfa82bf3771bd470b045686609aafb0d31dc774d3d636cd4c0511: cannot retrieve image configuration for manifest sha256:8a154e2401cbfa82bf3771bd470b045686609aafb0d31dc774d3d636cd4c0511: received unexpected HTTP status: 503 Service Unavailable`

**Comment by gabemontero** [comment]
ok the registry 503 apears to be a momentary hiccup

**Comment by gabemontero** [comment]
aws terraform flake image eco

/test e2e-aws-image-ecosystem

**Comment by adambkaplan** [comment]
/hold

This will have to wait until 4.4 is open :/

**Comment by adambkaplan** [comment]
/lgtm

Marking looks good so that when 4.4 is open we can merge right away.

**Comment by adambkaplan** [comment]
/hold cancel

New openapi requirements mean we need to land the rebase first.

**Comment by gabemontero** [comment]
samples operator upgraded fine:

```
           "status": {
                "conditions": [
                    {
                        "lastTransitionTime": "2019-11-06T17:29:01Z",
                        "message": "Samples installation successful at 0.0.1-2019-11-06-164704",
                        "status": "True",
                        "type": "Available"
                    },
                    {
                        "lastTransitionTime": "2019-11-06T17:29:01Z",
                        "message": "Samples installation successful at 0.0.1-2019-11-06-164704",
                        "status": "False",
                        "type": "Progressing"
                    },
                    {
                        "lastTransitionTime": "2019-11-06T17:09:52Z",
                        "status": "False",
                        "type": "Degraded"
                    }
```

/retest

**Pull request merged**
