### PR TITLE
BUILD-298: Bump k8s to 1.22.1

### PR DESCRIPTION
**Pull request by dperaza4dustbit**
Updating dependency and vendor copies as well.

### CODE REVIEW

**Comment by gabemontero** [comment]
maybe the same golang image we use for ocp is not available for okd builds ?

retesting the job to see if it is a flake

**Comment by gabemontero** [comment]
@vrutkovs - we seem to be experiencing DNS / networking issues with the OKD jobs.  Even the pull of the golang image in the image job is failing:

```
Get "https://registry.svc.ci.openshift.org/v2/": dial tcp: lookup registry.svc.ci.openshift.org on 172.30.0.10:53: no such host
```

is this something you are aware of?  Should we just skip, or is there something from an OKD CI perspective you want to investigate first?

thanks

**Comment by vrutkovs** [comment]
That's odd, I don't see this error in 4.9 nightlies

/retest

**Comment by gabemontero** [comment]
yeah still occurring @vrutkovs 

a diff between the samples operator setup in openshift/release and the periodics you mentioned ?

**Pull request merged**
