### PR TITLE
 Bug 1719037: upgrades while unmanaged/removed broken

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/sig-developer-experience fyi ... cherry pick of the master branch PR that just merged

### CODE REVIEW

**Comment by gabemontero** [comment]
FYI I've added `4.1.2` to the associated bugzilla's whiteboard to get it into the review/discussions for 4.1.2 inclusion

**Comment by derekwaynecarr** [comment]
is there a reason why the automated cherry pick was not used?  do we have any confirmation this works as intended in master?

**Comment by derekwaynecarr** [comment]
the change appears to have already been verified in 4.2 per https://bugzilla.redhat.com/show_bug.cgi?id=1718412

/cherry-pick-approved

**Comment by gabemontero** [comment]
did not use the bot cause it bugs me .... but I can use it moving forward if need be 

master PR is https://github.com/openshift/cluster-samples-operator/pull/151 and you caught the bz @derekwaynecarr thx

**Comment by derekwaynecarr** [comment]
actually i linked to wrong bz.

**Comment by gabemontero** [comment]
bz was 1718454 for master

**Comment by eparis** [comment]
looks like the (correct) parent PR was VERIFIED. Adding label.

**Pull request merged**
