### PR TITLE
add david peraza as approver, clean up reviewers

### PR DESCRIPTION
**Pull request by gabemontero**
/assign @dperaza4dustbit 

@dperaza4dustbit - the first test for your new privileges will be constructing a PR that adds whomever else you want as approver/reviewer ;-)

/assign @bparees 

1) do you want to be removed as an approver?
2) are you amenable to adding the valid bz label :-) ? .... adding @dperaza4dustbit as part of transferring samples to his team

### CODE REVIEW

**Comment by bparees** [comment]
yes please remove me as approver.  I can always manually apply labels anyway but i'd rather not have people pinging me thinking i'm a relevant approver
bz label added

**Comment by gabemontero** [comment]
> yes please remove me as approver. I can always manually apply labels anyway but i'd rather not have people pinging me thinking i'm a relevant approver
> bz label added

done and thanks @bparees

**Pull request merged**
