### PR TITLE
update Jenkins to use v4.12 imagestreams

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by gabemontero** [comment]
/approve

I'll defer for now at least on the lgtm to @fbm3307 for her question in https://github.com/openshift/cluster-samples-operator/pull/491#issuecomment-1441436786

I think this is minimally "related" to CVE maintenance (and what build-jenkins has to deal with in cpaas) if not a specific cve.  It certainly could be related to a CVE, but I can't say with certainty.  @coreydaley for sure can

**Comment by fbm3307** [comment]
@coreydaley since we have stopped accepting new tags or any updates starting ocp4.13 to the imagestreams/templates unless its a CVE or customer affecting bug, Please do give CVE/Bug number in this PR.

**Comment by coreydaley** [comment]
@fbm3307 Here is a list of CVE related bugs that are fixed in this image.

OCPBUGS-335
--
OCPBUGS-331
OCPBUGS-333
OCPBUGS-325
OCPBUGS-327
OCPBUGS-315
OCPBUGS-4440
OCPBUGS-6649
OCPBUGS-4060
OCPBUGS-3486
OCPBUGS-2549
OCPBUGS-2550
OCPBUGS-2703
OCPBUGS-2685
OCPBUGS-2715
OCPBUGS-2667
OCPBUGS-2673
OCPBUGS-2679
OCPBUGS-489
OCPBUGS-2709
OCPBUGS-2725
OCPBUGS-2691
OCPBUGS-905
OCPBUGS-914
OCPBUGS-329
OCPBUGS-323
OCPBUGS-1195
OCPBUGS-1095
OCPBUGS-1185
OCPBUGS-2697

**Comment by fbm3307** [comment]
@coreydaley please add ocpbug number to title, this PR requires that bug number to get merged

**Pull request merged**
