### PR TITLE
Bug 1804763: add imagestream for oauthproxy image

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero do we have any sort of test coverage for these imagestreams?

**Comment by bparees** [comment]
/hold
need @openshift/sig-auth acknowledgement since this is their image.

**Comment by mfojtik** [comment]
/cc @sttts 

I don't see problem shipping this via image stream as people can use it today anyway (and they do). ImageStream only makes it available for disconnected users.

**Comment by mfojtik** [comment]
/lgtm

Will wait for @sttts to unhold.

**Comment by gabemontero** [comment]
> @gabemontero do we have any sort of test coverage for these imagestreams?

Not as part of image-eco @bparees 

I've tangentially seen some of the used in CI in other contexts of course (must-gather for artifact collection ... don't recall if that uses cli or not).

**Comment by sttts** [comment]
/retest

As discussed on Slack with @bparees @jwforres @smarterclayton this only makes the image stream available to components outside of OpenShift core. This **does not imply any support or any future compatibility**. Flags will change.

/hold cancel

**Pull request merged**
