### PR TITLE
[release-4.15] OCPBUGS-37464: Set required-scc for openshift workloads

### PR DESCRIPTION
**Pull request by kramaranya**
[OCPBUGS-37464](https://issues.redhat.com/browse/OCPBUGS-37464)

Cherry-pick of #535

### CODE REVIEW

**Comment by gabemontero** [comment]
@fbm3307 @dperaza4dustbit - apologies for not finding it, but who should be approving these PRs now?  

thanks

**Comment by fbm3307** [comment]
@metlos @mfrancisc should be able to help you here

**Comment by mfrancisc** [comment]
@kramaranya I'm new to this project, my understanding is that this is backport fix from 4.16 correct ?

**Comment by kramaranya** [comment]
@mfrancisc yep, you're right!

**Comment by kramaranya** [comment]
> lgtm

@mfrancisc thanks! however the label wasn't added, could you please write it with a slash?

**Comment by mfrancisc** [comment]
> @mfrancisc thanks! however the label wasn't added, could you please write it with a slash?

@kramaranya I would be more then happy to do that, but I believe I need to be in the owners file , otherwise my approval doesn't matter :) See https://github.com/openshift/cluster-samples-operator/pull/549

Meanwhile maybe @fbm3307 can help with this 🙏

**Comment by kramaranya** [comment]
> I would be more then happy to do that, but I believe I need to be in the owners file

@mfrancisc oh makes sense, i guess now you can label it as that pr was merged :) thanks!

**Comment by mfrancisc** [comment]
I think I need to be owner also in the release-4.15 branch 🤦‍♂️  . See https://github.com/openshift/cluster-samples-operator/pull/550

**Comment by metlos** [comment]
@kramaranya, @fbm3307 is anyone of you able to add the above labels? seems like that's above my paygrade...

**Comment by kramaranya** [comment]
> kramaranya, fbm3307 is anyone of you able to add the above labels? seems like that's above my paygrade...

https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/cluster-samples-operator/_pluginconfig.yaml#L9 I guess @fbm3307 is able to add both labels

**Pull request merged**
