### PR TITLE
update jenkins CPaaS image refs to 4.11

### PR DESCRIPTION
**Pull request by jkhelil**

### CODE REVIEW

**Comment by jkhelil** [comment]
I can see infra or platform errors, hence retesting
`level=error msg=Bootstrap failed to complete: Get "https://api.ci-op-4ng911pp-af81a.origin-ci-int-aws.dev.rhcloud.com:6443/version": dial tcp 3.129.174.255:6443: connect: connection refused
level=error msg=Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane.
level=warning msg=The bootstrap machine is unable to resolve API and/or API-Int Server URLs
level=info msg=Successfully resolved API_INT_URL api-int.ci-op-4ng911pp-af81a.origin-ci-int-aws.dev.rhcloud.com
level=info msg=Unable to reach API_INT_URL's https endpoint at https://10.0.248.197:6443/version
`

**Comment by jkhelil** [comment]
Hi @fbm3307 , are you aware about issues on cluster creation
i have multiple errors like this on the failing tests
`error getting cluster version: Get "https://api.ci-op-4hfrsl3d-105a1.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusterversions/version": dial tcp 52.71.77.188:6443: connect: connection refused
ClusterID: 
ClusterVersion: Installing "" for <unknown>: <unknown>
error getting cluster operators: Get "https://api.ci-op-4hfrsl3d-105a1.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 52.71.77.188:6443: connect: connection refused
C`

**Comment by jkhelil** [comment]
@fbm3307 
I can see this in the e2e-aws-proxy logs
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/481/pull-ci-openshift-cluster-samples-operator-master-e2e-aws-proxy/1615645421231673344/build-log.txt
`

Ginkgo exit error 1: exit with code 1

failed: (50.1s) 2023-01-18T10:41:38 "[sig-network] NetworkPolicyLegacy [LinuxOnly] NetworkPolicy between server and client should ensure an IP overlapping both IPBlock.CIDR and IPBlock.Except is allowed [Feature:NetworkPolicy] [Skipped:Network/OpenShiftSDN/Multitenant] [Skipped:Network/OpenShiftSDN] [Suite:openshift/conformance/parallel] [Suite:k8s]"`

**Comment by fbm3307** [comment]
@jkhelil This PR needs to raised in the https://github.com/openshift/jenkins/tree/master/openshift/imagestreams repo. Cluster Samples Operator will pull those updates/changes during the next OCP release(OC4.13)

**Comment by jkhelil** [comment]
close this PR in favor https://github.com/openshift/jenkins/pull/1555

**Comment by gabemontero** [comment]
In case it was not clear from various skills transfers @fbm3307 @jkhelil @coreydaley, the process here should be
- build-jenkins team makes updates to its imagestreams like https://github.com/openshift/jenkins/pull/1555
- when that merges, the scheduled openshift/library sync, i.e. the one @coreydaley has overhauled in the past, will pick up the imagestream change
- Now, if the PR like https://github.com/openshift/jenkins/pull/1555 is say related to a Jenkins CVE, this is considered an bug and bumping the samples operator imagestream inventory to pull in those jenkins changes is warranted outside the scope of the normal per-release bump of samples that are done.

i.e. you would run https://github.com/openshift/cluster-samples-operator/blob/master/library-sync.sh but only include the jenkins changes.

**Comment by fbm3307** [comment]
@gabemontero  Thanks for this

**Pull request closed without merging**
