### PR TITLE
rename clusteroperator resource, align manifests dir name w/ other operators

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/cluster-samples-operator/issues/96

### CODE REVIEW

**Comment by bparees** [comment]
/hold

/assign @gabemontero 

this builds on top of your rhel enablement PR, so it should merge cleanly after yours merges, unless you have to make more changes to your PR.

**Comment by gabemontero** [comment]
new commit looks good to me @bparees

**Comment by bparees** [comment]
/assign @gabemontero 
(bot was dead)

**Comment by bparees** [comment]
unrelated failures
/retest

**Comment by bparees** [comment]
cluster-monitoring failed to go available
/test e2e-aws

**Comment by gabemontero** [comment]
do we still want to hold this @bparees ?

**Comment by bparees** [comment]
i'd like to see it pass e2e-aws a few times so we know we're not introducing something that's going to block the install.  Right now there's only one passing e2e-aws in the test history.

/refresh
/test e2e-aws

**Pull request merged**
