### PR TITLE
Bug 2027745: Allowing ImageStream creation when config registry empty

### PR DESCRIPTION
**Pull request by dperaza4dustbit**
By default the configured sample registry is empty. This is causing
image stream creating at update time to fail even when the allowed
image registries include registry.redhat.io, registry.access.redhat.com
and quay.io. This PR takes care of the default scenario.

### CODE REVIEW

**Comment by dperaza4dustbit** [comment]
> @dperaza4dustbit - the new verify task that was added 10 months ago with [d03f727](https://github.com/openshift/cluster-samples-operator/commit/d03f72763232e21214c451f9786ad7ee058e07a1) needs to pick up via a vendor bump [openshift/build-machinery-go@7e33a7e](https://github.com/openshift/build-machinery-go/commit/7e33a7eb4ce3955ce3500d6daa96859384d0702b)
> 
> So you'll need to include that vendor bump with a separate commit in order to get this PR to merge.
> 
> The code change itself looks OK to me, but I'd like to see a unit test added that verifies the permutations. Creating a new test that calls `imageConfigBlocksImageStreamCreation` is sufficient IMO.
> 
> thanks

This is the bump of dependencies: https://github.com/openshift/cluster-samples-operator/pull/407 @gabemontero

**Comment by dperaza4dustbit** [comment]
> @dperaza4dustbit - the new verify task that was added 10 months ago with [d03f727](https://github.com/openshift/cluster-samples-operator/commit/d03f72763232e21214c451f9786ad7ee058e07a1) needs to pick up via a vendor bump [openshift/build-machinery-go@7e33a7e](https://github.com/openshift/build-machinery-go/commit/7e33a7eb4ce3955ce3500d6daa96859384d0702b)
> 
> So you'll need to include that vendor bump with a separate commit in order to get this PR to merge.
> 
> The code change itself looks OK to me, but I'd like to see a unit test added that verifies the permutations. Creating a new test that calls `imageConfigBlocksImageStreamCreation` is sufficient IMO.
> 
> thanks

Vendor update, working on unit test

**Comment by gabemontero** [comment]
the e2e's are sufficiently green now @dperaza4dustbit ... the vendor update appears good to go

of course when you have the unit test you are working posted and we'll go from there

**Comment by gabemontero** [comment]
bunch of install fails with okd ... will try one more time, then skip

/retest

**Pull request merged**
