### PR TITLE
Bug 1825774: add back missing parts to make openshift-config namespace secret list…

### PR DESCRIPTION
**Pull request by gabemontero**
…er functional

got a little too aggressive in removing operator related bits for the openshift-config secret lister

still need to create a workqueue and informer to enable it to obtain the secret

even though we no longer copy the secret, still inspect it to make sure it has creds for registry.redhat.io

/assign @ricardomaraschini 
/assign @dmage 

if one of you all have cycles please review - thanks

### CODE REVIEW

**Comment by gabemontero** [comment]
was able to verify on a local cluster ... able to retrieve the secret now

**Comment by gabemontero** [comment]
> It looks good to me but I admit I don't understand exactly why we need to react to changes on these secrets. Would you mind explain a little bit in here?

Yep I'll add some comments in the code.  I gave a very terse summary in this PR's description, but perhaps too terse.  For posterity, I'll clarify here as well:
1) rather than use a vanilla client to access the openshift-config secrets, we want to use the lister/sharedinformer/workqueue controller apparatus so we get watches and caching (so we don't have to hit the api server whenever we access the data)
2) but you cannot just partially set that up, as I originally attempted in  https://github.com/openshift/cluster-samples-operator/pull/249
3) otherwise the cache never gets populated, and we get "not found" errors when we attempt to get secrets that actually exist

**Comment by gabemontero** [comment]
ok @ricardomaraschini I've added the comment explaining stuff ... let me know if you think that is sufficient, and if it is, I'll squash, etc.

thanks

**Comment by ricardomaraschini** [comment]
> ok @ricardomaraschini I've added the comment explaining stuff ... let me know if you think that is sufficient, and if it is, I'll squash, etc.
> 
> thanks

Yep, thanks for that extra explanation. Squash them and I will LGTM.

**Comment by gabemontero** [comment]
commits squashed @ricardomaraschini  - thanks

**Comment by gabemontero** [comment]
unit test flake gone

**Pull request merged**
