### PR TITLE
Library output

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees - fyi / ptal

### CODE REVIEW

**Comment by bparees** [comment]
we shouldn't need both "official" and "arch/x86_64/official"

**Comment by bparees** [comment]
also let's give the toplevel dir a better name.  "assets" or "library" or something.   `/tmp/build/library-master` is an odd/meaningless path.

`library/x86_64` and `library/ppc64le` should be sufficient?

**Comment by gabemontero** [comment]
the `tmp/build` sudirs stems from how `operator-sdk` works ... I could not get the image building to work if it was not under `tmp/build`

**Comment by gabemontero** [comment]
`library-master` was trying to convey the master branch of library ... despite our prior discussion about always pulling from openshift/library:master, I wanted to clarify

that said, we can always rename if need be later on

I'll change `library-master` to `assets`

**Comment by gabemontero** [comment]
@bparees pushed updates for you comments, except the `tmp/build` piece I explained in https://github.com/openshift/cluster-samples-operator/pull/6#issuecomment-417366637

**Comment by bparees** [comment]
> the tmp/build sudirs stems from how operator-sdk works

i think we're going to have to talk about how we build the operator image, because the way operator-sdk does it isn't a way we can easily support when we are building the operator images from within openshift, I do not believe.  But sure, whatever we need to do for now.

**Comment by bparees** [comment]
looks better, i'd say merge this and we can iterate if/when we can resolve the "/tmp/build" requirement.

(i'm also not sure we really need the "arch" dir in the assets path)

**Pull request merged**
