### PR TITLE
Update file/folder removal for library transition to golang

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by gabemontero** [comment]
@yselkowitz FYI ..... once this openshift/library & openshift/release stuff is sorted out, some minor tweaks to the sample operator import script to adjust to changes

**Comment by gabemontero** [comment]
I will pull @coreydaley 's changes here and try it out myself as well before tagging for merge

**Comment by gabemontero** [comment]
ok the library-sync.sh output looks acceptable given the just corrected openshift/library operators/ folder ... mostly modfications, with a few adds and few delete based on normal new item / deprecated item activity we see from release to release

```
	modified:   assets/operator/ocp-ppc64le/cakephp/templates/cakephp-mysql-example.json
	modified:   assets/operator/ocp-ppc64le/cakephp/templates/cakephp-mysql-persistent.json
	modified:   assets/operator/ocp-ppc64le/dancer/templates/dancer-mysql-example.json
	modified:   assets/operator/ocp-ppc64le/dancer/templates/dancer-mysql-persistent.json
	modified:   assets/operator/ocp-ppc64le/django/templates/django-psql-example.json
	modified:   assets/operator/ocp-ppc64le/django/templates/django-psql-persistent.json
	modified:   assets/operator/ocp-ppc64le/golang/imagestreams/golang-rhel7.json
	modified:   assets/operator/ocp-ppc64le/httpd/imagestreams/httpd-rhel7.json
	modified:   assets/operator/ocp-ppc64le/httpd/templates/httpd-example.json
	modified:   assets/operator/ocp-ppc64le/java/imagestreams/java-rhel7-ppc64le.json
	modified:   assets/operator/ocp-ppc64le/java/imagestreams/openjdk-11-rhel7-rhel7-ppc64le.json
	modified:   assets/operator/ocp-ppc64le/java/imagestreams/openjdk-11-rhel8-rhel7-ppc64le.json
	modified:   assets/operator/ocp-ppc64le/java/imagestreams/openjdk-8-rhel8-rhel7-ppc64le.json
	modified:   assets/operator/ocp-ppc64le/java/imagestreams/redhat-openjdk18-openshift-rhel7-ppc64le.json
	modified:   assets/operator/ocp-ppc64le/java/templates/openjdk-web-basic-s2i.json
	modified:   assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-agent-base-rhel7.json
	modified:   assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-agent-maven-rhel7.json
	modified:   assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-agent-nodejs-rhel7.json
	modified:   assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-rhel7.json
	modified:   assets/operator/ocp-ppc64le/jenkins/templates/jenkins-ephemeral-monitored.json
	modified:   assets/operator/ocp-ppc64le/jenkins/templates/jenkins-ephemeral.json
	modified:   assets/operator/ocp-ppc64le/jenkins/templates/jenkins-persistent-monitored.json
	modified:   assets/operator/ocp-ppc64le/jenkins/templates/jenkins-persistent.json
	modified:   assets/operator/ocp-ppc64le/mariadb/imagestreams/mariadb-rhel7.json
	modified:   assets/operator/ocp-ppc64le/mariadb/templates/mariadb-ephemeral.json
	modified:   assets/operator/ocp-ppc64le/mariadb/templates/mariadb-persistent.json
	modified:   assets/operator/ocp-ppc64le/mongodb/imagestreams/mongodb-rhel7-ppc64le.json
	modified:   assets/operator/ocp-ppc64le/mongodb/templates/mongodb-ephemeral.json
	modified:   assets/operator/ocp-ppc64le/mongodb/templates/mongodb-persistent.json
	modified:   assets/operator/ocp-ppc64le/mysql/imagestreams/mysql-rhel7.json
	modified:   assets/operator/ocp-ppc64le/mysql/templates/mysql-ephemeral.json
	modified:   assets/operator/ocp-ppc64le/mysql/templates/mysql-persistent.json
	modified:   assets/operator/ocp-ppc64le/nginx/imagestreams/nginx-rhel7-ppc64le.json
	modified:   assets/operator/ocp-ppc64le/nginx/templates/nginx-example.json
	modified:   assets/operator/ocp-ppc64le/nodejs/imagestreams/nodejs-rhel7.json
	modified:   assets/operator/ocp-ppc64le/nodejs/templates/nodejs-mongo-persistent.json
	modified:   assets/operator/ocp-ppc64le/nodejs/templates/nodejs-mongodb-example.json
	modified:   assets/operator/ocp-ppc64le/perl/imagestreams/perl-rhel7.json
	modified:   assets/operator/ocp-ppc64le/php/imagestreams/php-rhel7.json
	modified:   assets/operator/ocp-ppc64le/postgresql/imagestreams/postgresql-rhel7-ppc64le.json
	modified:   assets/operator/ocp-ppc64le/postgresql/templates/postgresql-ephemeral.json
	modified:   assets/operator/ocp-ppc64le/postgresql/templates/postgresql-persistent.json
	modified:   assets/operator/ocp-ppc64le/python/imagestreams/python-rhel7.json
	modified:   assets/operator/ocp-ppc64le/rails/templates/rails-pgsql-persistent.json
	modified:   assets/operator/ocp-ppc64le/rails/templates/rails-postgresql-example.json
	modified:   assets/operator/ocp-ppc64le/redis/imagestreams/redis-rhel7.json
	modified:   assets/operator/ocp-ppc64le/redis/templates/redis-ephemeral.json
	modified:   assets/operator/ocp-ppc64le/redis/templates/redis-persistent.json
	modified:   assets/operator/ocp-ppc64le/ruby/imagestreams/ruby-rhel7-ppc64le.json
	modified:   assets/operator/ocp-s390x/cakephp/templates/cakephp-mysql-example.json
	modified:   assets/operator/ocp-s390x/cakephp/templates/cakephp-mysql-persistent.json
	modified:   assets/operator/ocp-s390x/dancer/templates/dancer-mysql-example.json
	modified:   assets/operator/ocp-s390x/dancer/templates/dancer-mysql-persistent.json
	modified:   assets/operator/ocp-s390x/django/templates/django-psql-example.json
	modified:   assets/operator/ocp-s390x/django/templates/django-psql-persistent.json
	modified:   assets/operator/ocp-s390x/golang/imagestreams/golang-rhel7.json
	modified:   assets/operator/ocp-s390x/httpd/imagestreams/httpd-rhel7.json
	modified:   assets/operator/ocp-s390x/httpd/templates/httpd-example.json
	modified:   assets/operator/ocp-s390x/java/imagestreams/java-rhel7-s390x.json
	modified:   assets/operator/ocp-s390x/java/imagestreams/openjdk-11-rhel7-rhel7-s390x.json
	modified:   assets/operator/ocp-s390x/java/imagestreams/openjdk-11-rhel8-rhel7-s390x.json
	modified:   assets/operator/ocp-s390x/java/imagestreams/openjdk-8-rhel8-rhel7-s390x.json
	modified:   assets/operator/ocp-s390x/java/imagestreams/redhat-openjdk18-openshift-rhel7-s390x.json
	modified:   assets/operator/ocp-s390x/java/templates/openjdk-web-basic-s2i.json
	modified:   assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-agent-base-rhel7.json
	modified:   assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-agent-maven-rhel7.json
	modified:   assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-agent-nodejs-rhel7.json
	modified:   assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-rhel7.json
	modified:   assets/operator/ocp-s390x/jenkins/templates/jenkins-ephemeral-monitored.json
	modified:   assets/operator/ocp-s390x/jenkins/templates/jenkins-ephemeral.json
	modified:   assets/operator/ocp-s390x/jenkins/templates/jenkins-persistent-monitored.json
	modified:   assets/operator/ocp-s390x/jenkins/templates/jenkins-persistent.json
	modified:   assets/operator/ocp-s390x/mariadb/imagestreams/mariadb-rhel7.json
	modified:   assets/operator/ocp-s390x/mariadb/templates/mariadb-ephemeral.json
	modified:   assets/operator/ocp-s390x/mariadb/templates/mariadb-persistent.json
	modified:   assets/operator/ocp-s390x/mongodb/imagestreams/mongodb-rhel7-s390x.json
	modified:   assets/operator/ocp-s390x/mongodb/templates/mongodb-ephemeral.json
	modified:   assets/operator/ocp-s390x/mongodb/templates/mongodb-persistent.json
	modified:   assets/operator/ocp-s390x/mysql/imagestreams/mysql-rhel7.json
	modified:   assets/operator/ocp-s390x/mysql/templates/mysql-ephemeral.json
	modified:   assets/operator/ocp-s390x/mysql/templates/mysql-persistent.json
	modified:   assets/operator/ocp-s390x/nginx/imagestreams/nginx-rhel7-s390x.json
	modified:   assets/operator/ocp-s390x/nginx/templates/nginx-example.json
	modified:   assets/operator/ocp-s390x/nodejs/imagestreams/nodejs-rhel7.json
	modified:   assets/operator/ocp-s390x/nodejs/templates/nodejs-mongo-persistent.json
	modified:   assets/operator/ocp-s390x/nodejs/templates/nodejs-mongodb-example.json
	modified:   assets/operator/ocp-s390x/perl/imagestreams/perl-rhel7.json
	modified:   assets/operator/ocp-s390x/php/imagestreams/php-rhel7.json
	modified:   assets/operator/ocp-s390x/postgresql/imagestreams/postgresql-rhel7-s390x.json
	modified:   assets/operator/ocp-s390x/postgresql/templates/postgresql-ephemeral.json
	modified:   assets/operator/ocp-s390x/postgresql/templates/postgresql-persistent.json
	modified:   assets/operator/ocp-s390x/python/imagestreams/python-rhel7.json
	modified:   assets/operator/ocp-s390x/rails/templates/rails-pgsql-persistent.json
	modified:   assets/operator/ocp-s390x/rails/templates/rails-postgresql-example.json
	modified:   assets/operator/ocp-s390x/redis/imagestreams/redis-rhel7.json
	modified:   assets/operator/ocp-s390x/redis/templates/redis-ephemeral.json
	modified:   assets/operator/ocp-s390x/redis/templates/redis-persistent.json
	modified:   assets/operator/ocp-s390x/ruby/imagestreams/ruby-rhel7-s390x.json
	modified:   assets/operator/ocp-x86_64/3scale/imagestreams/apicast-gateway.json
	modified:   assets/operator/ocp-x86_64/3scale/templates/3scale-gateway.json
	modified:   assets/operator/ocp-x86_64/amq/imagestreams/jboss-amq-62-rhel7.json
	modified:   assets/operator/ocp-x86_64/amq/imagestreams/jboss-amq-63-rhel7.json
	modified:   assets/operator/ocp-x86_64/amq/templates/amq63-basic.json
	modified:   assets/operator/ocp-x86_64/amq/templates/amq63-persistent-ssl.json
	modified:   assets/operator/ocp-x86_64/amq/templates/amq63-persistent.json
	modified:   assets/operator/ocp-x86_64/amq/templates/amq63-ssl.json
	modified:   assets/operator/ocp-x86_64/cakephp/templates/cakephp-mysql-example.json
	modified:   assets/operator/ocp-x86_64/cakephp/templates/cakephp-mysql-persistent.json
	modified:   assets/operator/ocp-x86_64/dancer/templates/dancer-mysql-example.json
	modified:   assets/operator/ocp-x86_64/dancer/templates/dancer-mysql-persistent.json
	modified:   assets/operator/ocp-x86_64/datagrid/imagestreams/jboss-datagrid65-client-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/datagrid/imagestreams/jboss-datagrid65-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/datagrid/imagestreams/jboss-datagrid71-client-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/datagrid/imagestreams/jboss-datagrid71-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/datagrid/imagestreams/jboss-datagrid72-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/datagrid/imagestreams/jboss-datagrid73-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/datagrid/templates/cache-service.json
	modified:   assets/operator/ocp-x86_64/datagrid/templates/datagrid-service.json
	modified:   assets/operator/ocp-x86_64/datavirt/imagestreams/jboss-datavirt64-driver-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/datavirt/imagestreams/jboss-datavirt64-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/datavirt/templates/datavirt64-basic-s2i.json
	modified:   assets/operator/ocp-x86_64/datavirt/templates/datavirt64-extensions-support-s2i.json
	modified:   assets/operator/ocp-x86_64/datavirt/templates/datavirt64-ldap-s2i.json
	modified:   assets/operator/ocp-x86_64/datavirt/templates/datavirt64-secure-s2i.json
	modified:   assets/operator/ocp-x86_64/decisionserver/imagestreams/jboss-decisionserver64-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/decisionserver/templates/decisionserver64-amq-s2i.json
	modified:   assets/operator/ocp-x86_64/decisionserver/templates/decisionserver64-basic-s2i.json
	modified:   assets/operator/ocp-x86_64/django/templates/django-psql-example.json
	modified:   assets/operator/ocp-x86_64/django/templates/django-psql-persistent.json
	modified:   assets/operator/ocp-x86_64/dotnet/imagestreams/dotnet-rhel7.json
	modified:   assets/operator/ocp-x86_64/dotnet/imagestreams/dotnet-runtime-rhel7.json
	modified:   assets/operator/ocp-x86_64/dotnet/templates/dotnet-example.json
	modified:   assets/operator/ocp-x86_64/dotnet/templates/dotnet-pgsql-persistent.json
	modified:   assets/operator/ocp-x86_64/eap-cd/imagestreams/eap-cd-openshift-rhel8.json
	modified:   assets/operator/ocp-x86_64/eap-cd/imagestreams/eap-cd-runtime-openshift-rhel8.json
	modified:   assets/operator/ocp-x86_64/eap-cd/templates/eap-cd-basic-s2i.json
	modified:   assets/operator/ocp-x86_64/eap-cd/templates/eap-cd-starter-s2i.json
	modified:   assets/operator/ocp-x86_64/eap/imagestreams/jboss-eap64-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/eap/imagestreams/jboss-eap70-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/eap/imagestreams/jboss-eap71-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/eap/imagestreams/jboss-eap72-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/eap/templates/eap72-basic-s2i.json
	modified:   assets/operator/ocp-x86_64/eap/templates/eap72-https-s2i.json
	modified:   assets/operator/ocp-x86_64/eap/templates/eap72-mongodb-persistent-s2i.json
	modified:   assets/operator/ocp-x86_64/eap/templates/eap72-mongodb-s2i.json
	modified:   assets/operator/ocp-x86_64/eap/templates/eap72-mysql-persistent-s2i.json
	modified:   assets/operator/ocp-x86_64/eap/templates/eap72-mysql-s2i.json
	modified:   assets/operator/ocp-x86_64/eap/templates/eap72-postgresql-persistent-s2i.json
	modified:   assets/operator/ocp-x86_64/eap/templates/eap72-postgresql-s2i.json
	modified:   assets/operator/ocp-x86_64/eap/templates/eap72-sso-s2i.json
	modified:   assets/operator/ocp-x86_64/eap/templates/eap72-third-party-db-s2i.json
	modified:   assets/operator/ocp-x86_64/fis/imagestreams/apicurito-ui-rhel7.json
	modified:   assets/operator/ocp-x86_64/fis/imagestreams/fis-java-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/fis/imagestreams/fis-karaf-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/fis/imagestreams/fuse-apicurito-generator-rhel7.json
	modified:   assets/operator/ocp-x86_64/fis/imagestreams/fuse7-console-rhel7.json
	modified:   assets/operator/ocp-x86_64/fis/imagestreams/fuse7-eap-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/fis/imagestreams/fuse7-java-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/fis/imagestreams/fuse7-karaf-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/fis/imagestreams/jboss-fuse70-console-rhel7.json
	modified:   assets/operator/ocp-x86_64/fis/imagestreams/jboss-fuse70-eap-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/fis/imagestreams/jboss-fuse70-java-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/fis/imagestreams/jboss-fuse70-karaf-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/fis/templates/apicurito.json
	deleted:    assets/operator/ocp-x86_64/fis/templates/fuse75-console.json
	modified:   assets/operator/ocp-x86_64/fis/templates/fuse76-console.json
	deleted:    assets/operator/ocp-x86_64/fis/templates/s2i-fuse75-spring-boot-camel-rest-3scale.json
	deleted:    assets/operator/ocp-x86_64/fis/templates/s2i-fuse75-spring-boot-camel-xml.json
	deleted:    assets/operator/ocp-x86_64/fis/templates/s2i-fuse75-spring-boot-camel.json
	modified:   assets/operator/ocp-x86_64/fis/templates/s2i-fuse76-spring-boot-camel-rest-3scale.json
	modified:   assets/operator/ocp-x86_64/fis/templates/s2i-fuse76-spring-boot-camel-xml.json
	modified:   assets/operator/ocp-x86_64/fis/templates/s2i-fuse76-spring-boot-camel.json
	modified:   assets/operator/ocp-x86_64/golang/imagestreams/golang-rhel7.json
	modified:   assets/operator/ocp-x86_64/httpd/imagestreams/httpd-rhel7.json
	modified:   assets/operator/ocp-x86_64/httpd/templates/httpd-example.json
	modified:   assets/operator/ocp-x86_64/java/imagestreams/java-rhel7.json
	modified:   assets/operator/ocp-x86_64/java/imagestreams/openjdk-11-rhel7-rhel7.json
	modified:   assets/operator/ocp-x86_64/java/imagestreams/openjdk-11-rhel8-rhel7.json
	deleted:    assets/operator/ocp-x86_64/java/imagestreams/openjdk-8-rhel8-rhel7.json
	modified:   assets/operator/ocp-x86_64/java/imagestreams/redhat-openjdk18-openshift-rhel7.json
	new file:   assets/operator/ocp-x86_64/java/imagestreams/ubi8-openjdk-11-rhel7.json
	new file:   assets/operator/ocp-x86_64/java/imagestreams/ubi8-openjdk-8-rhel7.json
	modified:   assets/operator/ocp-x86_64/java/templates/openjdk-web-basic-s2i.json
	new file:   assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-agent-base-rhel7.json
	modified:   assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-agent-maven-rhel7.json
	modified:   assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-agent-nodejs-rhel7.json
	modified:   assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-rhel7.json
	modified:   assets/operator/ocp-x86_64/jenkins/templates/jenkins-ephemeral-monitored.json
	modified:   assets/operator/ocp-x86_64/jenkins/templates/jenkins-ephemeral.json
	modified:   assets/operator/ocp-x86_64/jenkins/templates/jenkins-persistent-monitored.json
	modified:   assets/operator/ocp-x86_64/jenkins/templates/jenkins-persistent.json
	modified:   assets/operator/ocp-x86_64/mariadb/imagestreams/mariadb-rhel7.json
	modified:   assets/operator/ocp-x86_64/mariadb/templates/mariadb-ephemeral.json
	modified:   assets/operator/ocp-x86_64/mariadb/templates/mariadb-persistent.json
	modified:   assets/operator/ocp-x86_64/mongodb/imagestreams/mongodb-rhel7.json
	modified:   assets/operator/ocp-x86_64/mongodb/templates/mongodb-ephemeral.json
	modified:   assets/operator/ocp-x86_64/mongodb/templates/mongodb-persistent.json
	modified:   assets/operator/ocp-x86_64/mysql/imagestreams/mysql-rhel7.json
	modified:   assets/operator/ocp-x86_64/mysql/templates/mysql-ephemeral.json
	modified:   assets/operator/ocp-x86_64/mysql/templates/mysql-persistent.json
	modified:   assets/operator/ocp-x86_64/nginx/imagestreams/nginx-rhel7.json
	modified:   assets/operator/ocp-x86_64/nginx/templates/nginx-example.json
	modified:   assets/operator/ocp-x86_64/nodejs/imagestreams/nodejs-rhel7.json
	modified:   assets/operator/ocp-x86_64/nodejs/templates/nodejs-mongo-persistent.json
	modified:   assets/operator/ocp-x86_64/nodejs/templates/nodejs-mongodb-example.json
	modified:   assets/operator/ocp-x86_64/perl/imagestreams/perl-rhel7.json
	modified:   assets/operator/ocp-x86_64/php/imagestreams/php-rhel7.json
	modified:   assets/operator/ocp-x86_64/postgresql/imagestreams/postgresql-rhel7.json
	modified:   assets/operator/ocp-x86_64/postgresql/templates/postgresql-ephemeral.json
	modified:   assets/operator/ocp-x86_64/postgresql/templates/postgresql-persistent.json
	modified:   assets/operator/ocp-x86_64/processserver/imagestreams/jboss-processserver64-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/processserver/templates/processserver64-amq-mysql-persistent-s2i.json
	modified:   assets/operator/ocp-x86_64/processserver/templates/processserver64-amq-mysql-s2i.json
	modified:   assets/operator/ocp-x86_64/processserver/templates/processserver64-amq-postgresql-persistent-s2i.json
	modified:   assets/operator/ocp-x86_64/processserver/templates/processserver64-amq-postgresql-s2i.json
	modified:   assets/operator/ocp-x86_64/processserver/templates/processserver64-basic-s2i.json
	modified:   assets/operator/ocp-x86_64/processserver/templates/processserver64-externaldb-s2i.json
	modified:   assets/operator/ocp-x86_64/processserver/templates/processserver64-mysql-persistent-s2i.json
	modified:   assets/operator/ocp-x86_64/processserver/templates/processserver64-mysql-s2i.json
	modified:   assets/operator/ocp-x86_64/processserver/templates/processserver64-postgresql-persistent-s2i.json
	modified:   assets/operator/ocp-x86_64/python/imagestreams/python-rhel7.json
	modified:   assets/operator/ocp-x86_64/rails/templates/rails-pgsql-persistent.json
	modified:   assets/operator/ocp-x86_64/rails/templates/rails-postgresql-example.json
	modified:   assets/operator/ocp-x86_64/redis/imagestreams/redis-rhel7.json
	modified:   assets/operator/ocp-x86_64/redis/templates/redis-ephemeral.json
	modified:   assets/operator/ocp-x86_64/redis/templates/redis-persistent.json
	modified:   assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm-decisioncentral-rhel8.json
	modified:   assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm-kieserver-rhel8.json
	modified:   assets/operator/ocp-x86_64/rhdm/templates/rhdm77-authoring-ha.json
	modified:   assets/operator/ocp-x86_64/rhdm/templates/rhdm77-authoring.json
	modified:   assets/operator/ocp-x86_64/rhdm/templates/rhdm77-kieserver.json
	modified:   assets/operator/ocp-x86_64/rhdm/templates/rhdm77-prod-immutable-kieserver-amq.json
	modified:   assets/operator/ocp-x86_64/rhdm/templates/rhdm77-prod-immutable-kieserver.json
	modified:   assets/operator/ocp-x86_64/rhdm/templates/rhdm77-trial-ephemeral.json
	modified:   assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam-businesscentral-monitoring-rhel8.json
	modified:   assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam-businesscentral-rhel8.json
	modified:   assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam-kieserver-rhel8.json
	modified:   assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam-smartrouter-rhel8.json
	modified:   assets/operator/ocp-x86_64/rhpam/templates/rhpam77-authoring-ha.json
	modified:   assets/operator/ocp-x86_64/rhpam/templates/rhpam77-authoring.json
	modified:   assets/operator/ocp-x86_64/rhpam/templates/rhpam77-kieserver-externaldb.json
	modified:   assets/operator/ocp-x86_64/rhpam/templates/rhpam77-kieserver-mysql.json
	modified:   assets/operator/ocp-x86_64/rhpam/templates/rhpam77-kieserver-postgresql.json
	modified:   assets/operator/ocp-x86_64/rhpam/templates/rhpam77-managed.json
	modified:   assets/operator/ocp-x86_64/rhpam/templates/rhpam77-prod-immutable-kieserver-amq.json
	modified:   assets/operator/ocp-x86_64/rhpam/templates/rhpam77-prod-immutable-kieserver.json
	modified:   assets/operator/ocp-x86_64/rhpam/templates/rhpam77-prod-immutable-monitor.json
	modified:   assets/operator/ocp-x86_64/rhpam/templates/rhpam77-prod.json
	modified:   assets/operator/ocp-x86_64/rhpam/templates/rhpam77-trial-ephemeral.json
	modified:   assets/operator/ocp-x86_64/ruby/imagestreams/ruby-rhel7.json
	modified:   assets/operator/ocp-x86_64/sso/imagestreams/redhat-sso70-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/sso/imagestreams/redhat-sso71-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/sso/imagestreams/redhat-sso72-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/sso/imagestreams/redhat-sso73-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/sso/imagestreams/sso74-openshift-rhel8.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso72-https.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso72-mysql-persistent.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso72-mysql.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso72-postgresql-persistent.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso72-postgresql.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso73-https.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso73-mysql-persistent.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso73-mysql.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso73-ocp4-x509-https.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso73-ocp4-x509-mysql-persistent.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso73-ocp4-x509-postgresql-persistent.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso73-postgresql-persistent.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso73-postgresql.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso74-https.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso74-ocp4-x509-https.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso74-ocp4-x509-postgresql-persistent.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso74-postgresql-persistent.json
	modified:   assets/operator/ocp-x86_64/sso/templates/sso74-postgresql.json
	modified:   assets/operator/ocp-x86_64/webserver/imagestreams/jboss-webserver30-tomcat7-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/webserver/imagestreams/jboss-webserver30-tomcat8-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/webserver/imagestreams/jboss-webserver31-tomcat7-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/webserver/imagestreams/jboss-webserver31-tomcat8-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/webserver/imagestreams/jboss-webserver50-tomcat9-openshift-rhel7.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-basic-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-https-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-mongodb-persistent-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-mongodb-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-mysql-persistent-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-mysql-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-postgresql-persistent-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat7-postgresql-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat8-basic-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat8-https-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat8-mongodb-persistent-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat8-mongodb-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat8-mysql-persistent-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat8-mysql-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws31-tomcat8-postgresql-persistent-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws50-tomcat9-basic-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws50-tomcat9-https-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws50-tomcat9-mongodb-persistent-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws50-tomcat9-mongodb-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws50-tomcat9-mysql-persistent-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws50-tomcat9-mysql-s2i.json
	modified:   assets/operator/ocp-x86_64/webserver/templates/jws50-tomcat9-postgresql-persistent-s2i.json

```

/lgtm

**Comment by yselkowitz** [comment]
> ok the library-sync.sh output looks acceptable given the just corrected openshift/library operators/ folder ... mostly modfications, with a few adds and few delete based on normal new item / deprecated item activity we see from release to release

Results looks sane to me.

**Pull request merged**
