### PR TITLE
Bug 1950808: add DeepCopy to avoid SharedInformer cache mutation

### PR DESCRIPTION
**Pull request by gabemontero**
adjust fsm status update grouping to account for deepcopies
reduce logging

manual pick of https://github.com/openshift/cluster-samples-operator/pull/369 for 4.7.z

bz set up so bots don't work well

### CODE REVIEW

**Comment by gabemontero** [comment]
/assign @adambkaplan 

this is the same change you just lgtm'ed in master/4.8 yesterday

to expedite my verifications I did the `git cherry-pick` manually in a 4.7 based branch vs. waiting to use the bot

**Comment by xiuwang** [comment]
Following the steps the customer did, samples operator don't restart anymore. There are no the errors shown mentioned in the bug.
Test on cluster launched from pr 4.7.0-0.ci.test-2021-04-21-023336-ci-ln-84xyi9k .

/label qe-approved

**Pull request merged**
