### PR TITLE
Bug 1881135: remove mongodb templates

### PR DESCRIPTION
**Pull request by yselkowitz**
The nodejs-ex templates are replaced by new ones from nodejs-rest-http-crud
which use postgresql.  JWS already had mysql and postgresql templates
alongside the mongodb ones.

Depends on https://github.com/openshift/origin/pull/25528

/hold

### CODE REVIEW

**Comment by gabemontero** [comment]
the jenkins e2e's were using the nodejs-mongodb template as well:

`new-app returned an error;\n{err=error:  local file access failed with: stat nodejs-mongodb-example`

So another update to openshift/origin will be needed.  Minimally https://github.com/openshift/origin/blob/master/test/extended/builds/pipeline_jenkins_e2e.go

**Comment by gabemontero** [comment]
e2e-aws looks like unrelated flakes

/test e2e-aws

**Comment by gabemontero** [comment]
So for pulling in https://github.com/openshift/library/pull/257 @yselkowitz to you want to re-purpose this PR or create a new one ?

**Comment by yselkowitz** [comment]
I'll use this one, just waiting for library to sync to update the PR.

**Comment by gabemontero** [comment]
degraded install okd operator ... samples operator was not degraded

/test okd-e2e-aws-operator

**Comment by yselkowitz** [comment]
CI has passed, but still need approved/lgtm to merge.

**Pull request merged**
