### PR TITLE
OCPBUGS-6579: update sample imagestreams with latest 4.11 image using specific image tag reference

### PR DESCRIPTION
**Pull request by jkhelil**
…e tag reference

### CODE REVIEW

**Comment by jkhelil** [comment]
/retitle OCPBUGS-6579: update sample imagestreams with latest 4.11 image using specific image tag reference

**Comment by coreydaley** [comment]
/assign @gabemontero 
for approval

**Review by gabemontero — APPROVED** [review]
looks in sync with 

https://github.com/openshift/library/blob/master/official/jenkins/imagestreams/jenkins-agent-base-rhel.json

and 

https://github.com/openshift/library/blob/master/official/jenkins/imagestreams/jenkins-rhel.json

and across the relevant arch's

/approve

**Comment by gabemontero** [comment]
we should run the jenkins e2e (it at least used to be on this repo), just a sec I'm checking 

/hold

**Comment by gabemontero** [comment]
/test e2e-aws-jenkins

should run https://github.com/openshift/origin/blob/master/test/extended/builds/pipeline_origin_bld.go

**Comment by coreydaley** [comment]
/hold cancel
e2e-aws-jenkins passed

**Comment by fbm3307** [comment]
@gabemontero @coreydaley Thanks for pitching in and approving the PR.
My understanding for CVE was that once the changes are done at Jenkins repo, I will have to run the library sync for this particular change. But i see here a manual update via a PR.?

Also i see ci/prow/e2e-aws-proxy test failing, May be not a related reason and also its in not required test .

**Comment by gabemontero** [comment]
> @gabemontero @coreydaley Thanks for pitching in and approving the PR. My understanding for CVE was that once the changes are done at Jenkins repo, I will have to run the library sync for this particular change. But i see here a manual update via a PR.?

running the fully library sync could have brought in other changes besides the jenkins one, which *technically* are not required to satisfy the jenkins cve

in the future if you all no longer mind that, sure, go ahead; otherwise, the approach @jkhelil took certainly suffices IMO

another alternative long term would be to add a new sync script that just deals with jenkins, since we now jenkins cve are a constant occurrence; @fbm3307 I'll leave it between you and @coreydaley  to sort out if someone from your two team takes that on

> 
> Also i see ci/prow/e2e-aws-proxy test failing, May be not a related reason and also its in not required test ?

yeah I see no way where a jenkins update would break e2e-aws-proxy, and as such, was not required for merging this

**Pull request merged**
