### PR TITLE
 reconcile status when clusteroperator changes

### PR DESCRIPTION
**Pull request by sanchezl**
Needed for https://github.com/openshift/cluster-kube-apiserver-operator/pull/1423.

If status is modified, the operator must set status to proper values. This ensures that accidents cannot permanently reset status and gives a clear indication that the operator is "live". This came up as important when operators were NOT live, during cert rotations and we had no indication of problems.

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

worked on clusterbot approving

**Comment by fbm3307** [comment]
@sanchezl @deads2k make sure all the required test pass before approving this PR

**Comment by deads2k** [comment]
> @sanchezl @deads2k Please make sure all the required test pass before approving this PR

It won't merge until tests pass

**Pull request merged**
