### PR TITLE
switch to mysql:8 and enable auth plugin needed for running in openshift

### PR DESCRIPTION
**Pull request by gabemontero**
Pull in fix for https://bugzilla.redhat.com/show_bug.cgi?id=1793116

upstream version:  https://github.com/sclorg/cakephp-ex/pull/116

### CODE REVIEW

**Comment by gabemontero** [comment]
OK @hhorak @yselkowitz ... if you look at the test results from https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-samples-operator/308/pull-ci-openshift-cluster-samples-operator-master-e2e-aws-image-ecosystem/1288136122261573632

On our debug of the failure, we see 

```
Jul 28 17:30:50.444: INFO: Running 'oc --namespace=e2e-test-cakephp-mysql-repo-test-7qshr --kubeconfig=/var/run/secrets/ci.openshift.io/multi-stage/kubeconfig logs pod/cakephp-mysql-example-1-deploy -c deployment -n e2e-test-cakephp-mysql-repo-test-7qshr'
Jul 28 17:30:50.997: INFO: Log for pod "cakephp-mysql-example-1-deploy"/"deployment"
---->
--> pre: Running hook pod ...
using migration paths 
 - /opt/app-root/src/config/Migrations
using seed paths 
 - /opt/app-root/src/config/Seeds
Exception: There was a problem connecting to the database: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client in [/opt/app-root/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php, line 127]
2020-07-28 17:15:56 Error: [InvalidArgumentException] There was a problem connecting to the database: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client in /opt/app-root/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php on line 127
Stack Trace:
#0 /opt/app-root/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(136): Phinx\Db\Adapter\MysqlAdapter->connect()
#1 /opt/app-root/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(469): Phinx\Db\Adapter\PdoAdapter->getConnection()
#2 /opt/app-root/src/vendor/cakephp/migrations/src/CakeAdapter.php(56): Phinx\Db\Adapter\AdapterWrapper->getConnection()
#3 /opt/app-root/src/vendor/cakephp/migrations/src/Command/CommandTrait.php(78): Migrations\CakeAdapter->__construct(Object(Phinx\Db\Adapter\TimedOutputAdapter), Object(Cake\Database\Connection))
#4 /opt/app-root/src/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(74): Migrations\Command\Migrate->bootstrap(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /opt/app-root/src/vendor/cakephp/migrations/src/Command/CommandTrait.php(35): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /opt/app-root/src/vendor/cakephp/migrations/src/Command/Migrate.php(67): Migrations\Command\Migrate->parentExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /opt/app-root/src/vendor/symfony/console/Command/Command.php(255): Migrations\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /opt/app-root/src/vendor/symfony/console/Application.php(960): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /opt/app-root/src/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Migrations\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /opt/app-root/src/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /opt/app-root/src/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /opt/app-root/src/vendor/cakephp/cakephp/src/Console/Shell.php(532): Migrations\Shell\MigrationsShell->main('migrations', 'migrate')
#13 /opt/app-root/src/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(164): Cake\Console\Shell->runCommand(Array, true, Array)
#14 /opt/app-root/src/vendor/cakephp/cakephp/src/Console/CommandRunner.php(342): Migrations\Shell\MigrationsShell->runCommand(Array, true)
#15 /opt/app-root/src/vendor/cakephp/cakephp/src/Console/CommandRunner.php(164): Cake\Console\CommandRunner->runShell(Object(Migrations\Shell\MigrationsShell), Array)
#16 /opt/app-root/src/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#17 {main}
```

Is that not the same thing originally tracked in https://github.com/sclorg/mysql-container/pull/280 and ultimately https://bugzilla.redhat.com/show_bug.cgi?id=1793116 ?

**Comment by gabemontero** [comment]
Reminder, the mysql image being used is registry.redhat.io/rhscl/mysql-80-rhel7:latest

**Comment by yselkowitz** [comment]
Could we try again with https://github.com/sclorg/cakephp-ex/pull/114 applied to the templates?

**Comment by gabemontero** [comment]
Yes I was commenting just that in https://github.com/sclorg/cakephp-ex/pull/114 :)

**Comment by gabemontero** [comment]
if https://github.com/openshift/cluster-samples-operator/pull/308/commits/7a329121a21ae82bbed7468c38b4ecae58819a4c work x86 my preference would be to have https://github.com/sclorg/cakephp-ex/pull/114 expand to make sure it hits both ephemeral and persistent storage options as well as all arch's and then pull it in via our normal openshift/library process

for now, I've only patched the x86 versions to accommodate the e2e's

**Comment by gabemontero** [comment]
problem still exists

```
        - name: MYSQL_DEFAULT_AUTHENTICATION_PLUGIN
          value: mysql_native_password
```

And still have 

```
--> pre: Running hook pod ...
using migration paths 
 - /opt/app-root/src/config/Migrations
using seed paths 
 - /opt/app-root/src/config/Seeds
Exception: There was a problem connecting to the database: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client in [/opt/app-root/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php, line 127]
2020-07-28 19:39:47 Error: [InvalidArgumentException] There was a problem connecting to the database: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client in /opt/app-root/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php on line 127
Stack Trace:
#0 /opt/app-root/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(136): Phinx\Db\Adapter\MysqlAdapter->connect()
#1 /opt/app-root/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(469): Phinx\Db\Adapter\PdoAdapter->getConnection()
#2 /opt/app-root/src/vendor/cakephp/migrations/src/CakeAdapter.php(56): Phinx\Db\Adapter\AdapterWrapper->getConnection()
#3 /opt/app-root/src/vendor/cakephp/migrations/src/Command/CommandTrait.php(78): Migrations\CakeAdapter->__construct(Object(Phinx\Db\Adapter\TimedOutputAdapter), Object(Cake\Database\Connection))
#4 /opt/app-root/src/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(74): Migrations\Command\Migrate->bootstrap(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /opt/app-root/src/vendor/cakephp/migrations/src/Command/CommandTrait.php(35): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /opt/app-root/src/vendor/cakephp/migrations/src/Command/Migrate.php(67): Migrations\Command\Migrate->parentExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /opt/app-root/src/vendor/symfony/console/Command/Command.php(255): Migrations\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /opt/app-root/src/vendor/symfony/console/Application.php(960): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /opt/app-root/src/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Migrations\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /opt/app-root/src/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /opt/app-root/src/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /opt/app-root/src/vendor/cakephp/cakephp/src/Console/Shell.php(532): Migrations\Shell\MigrationsShell->main('migrations', 'migrate')
#13 /opt/app-root/src/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(164): Cake\Console\Shell->runCommand(Array, true, Array)
#14 /opt/app-root/src/vendor/cakephp/cakephp/src/Console/CommandRunner.php(342): Migrations\Shell\MigrationsShell->runCommand(Array, true)
#15 /opt/app-root/src/vendor/cakephp/cakephp/src/Console/CommandRunner.php(164): Cake\Console\CommandRunner->runShell(Object(Migrations\Shell\MigrationsShell), Array)
#16 /opt/app-root/src/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#17 {main}

```

**Comment by yselkowitz** [comment]
Unless I'm misreading this, I have to wonder if the first hunk of each file is misplaced, instead of being added at line 232 with the other variables of the cakephp container, shouldn't it be added with the rest of the variables used in the mysql container?

https://github.com/openshift/cluster-samples-operator/blob/7a329121a21ae82bbed7468c38b4ecae58819a4c/assets/operator/ocp-x86_64/cakephp/templates/cakephp-mysql-example.json#L342-L365
https://github.com/openshift/cluster-samples-operator/blob/7a329121a21ae82bbed7468c38b4ecae58819a4c/assets/operator/ocp-x86_64/cakephp/templates/cakephp-mysql-persistent.json#L359-L382

**Comment by gabemontero** [comment]
https://github.com/sclorg/cakephp-ex/pull/114 has it on the cakephp DC but I've just pushed a commit that sets it on both DCs ... we'll see what happens

**Comment by yselkowitz** [comment]
Well, that passed CI.  Want to humour me and define the variables only in the mysql DC?

**Comment by yselkowitz** [comment]
/retest
Error messages look unrelated.

**Comment by gabemontero** [comment]
ok so only set on the mysql DC seems to be the ticket per your intuition @yselkowitz 

will repackage this PR to introduce this override short term (as that will help @vrutkovs out) while working on submitting the properly alternative upstream

**Comment by gabemontero** [comment]
though @vrutkovs the okd templates are not in the right spot under the assets dir ... see https://github.com/openshift/cluster-samples-operator/tree/master/assets/operator/okd-x86_64/official .... that `official` subdir is incorrect.

So I'll fix the cakephp mysql templates separately, after that `official` subdir thing gets fixed (I think I can get to it later today if you do not beat me to it).

**Comment by yselkowitz** [comment]
Don't the okd-x86_64 copies also need the variables added?

**Comment by gabemontero** [comment]
> Don't the okd-x86_64 copies also need the variables added?

yes but we'll fix that after @vrutkovs 's PR to fix the okd asset layout lands

**Comment by yselkowitz** [comment]
ok in that case
/lgtm

**Pull request merged**
