### PR TITLE
Bug 1755115: turn on scheduled import for payload imagestreams not managed by samp…

### PR DESCRIPTION
**Pull request by gabemontero**
…les operator

/hold

@smarterclayton @bparees @adambkaplan @dmage I'll launch a cluster via cluster-bot from this PR after the e2e's run, and see what the imagestream statuses look like in real time.

### CODE REVIEW

**Comment by gabemontero** [comment]
per current validation at https://github.com/openshift/openshift-apiserver/blob/master/pkg/image/apis/image/validation/validation.go#L264-L278 these imagestream updates should fail

discussing changes to the validation and other related threads in forum-devex

**Comment by gabemontero** [comment]
once https://github.com/openshift/openshift-controller-manager/pull/29 and https://github.com/openshift/openshift-apiserver/pull/28 merge, we can retry this / unhold it.

**Comment by bparees** [comment]
neat, you broke bugzilla :)

**Comment by gabemontero** [comment]
terraform flake on e2e-aws

/test e2e-aws

**Comment by gabemontero** [comment]
hmmm ... something is amiss with the must-gather tests ... could be related to this change ... investigating.

**Comment by gabemontero** [comment]
Yeah there is not status for the tags with these payload imagestreams.  For example:

```
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: 2019-09-27T15:01:30Z
    generation: 1
    name: must-gather
    namespace: openshift
    resourceVersion: "14475"
    selfLink: /apis/image.openshift.io/v1/namespaces/openshift/imagestreams/must-gather
    uid: bf27541c-478c-4e6c-836e-27b7d7e955c2
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: registry.svc.ci.openshift.org/ci-op-h7wz9g92/stable@sha256:de04c6df8404216773aa0a33ab82750724d3a472528aaf799a9d8b85dbc9f6b5
      generation: 1
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: image-registry.openshift-image-registry.svc:5000/openshift/must-gather
```

Seeing if I can find an event or image registry log to explain why.

@bparees @smarterclayton @dmage fyi ^^

**Comment by gabemontero** [comment]
Found it in the OCM log:

`E0927 15:03:09.809973       1 imagestream_controller.go:135] Error syncing image stream "openshift/must-gather": ImageStreamImport.image.openshift.io "must-gather" is invalid: spec.images[0].from.name: Invalid value: "registry.svc.ci.openshift.org/ci-op-h7wz9g92/stable@sha256:de04c6df8404216773aa0a33ab82750724d3a472528aaf799a9d8b85dbc9f6b5": only tags can be scheduled for import`

turns out there is another spot in the openshift-apiserver validation logic that is preventing scheduling for regs with canonical sha/digests.

https://github.com/openshift/openshift-apiserver/blob/master/pkg/image/apis/image/validation/validation.go#L542-L546

@bparees @smarterclayton @dmage ^^

I'll craft another PR

**Comment by gabemontero** [comment]
e2e-aws must-gather test ran successfully ... we're over the hump from a functional perspective

**Pull request merged**
