### PR TITLE
update sample imagestreams with latest 4.11 image using specific image tag reference

### PR DESCRIPTION
**Pull request by jkhelil**
…e tag reference

### CODE REVIEW

**Comment by gabemontero** [comment]
need the various bug approval labels @jkhelil @coreydaley

**Comment by coreydaley** [comment]
@jkhelil Shouldn't we be using the 4.12 images on this branch?

**Comment by gabemontero** [comment]
> @jkhelil Shouldn't we be using the 4.12 images on this branch?

I thought one of the big selling points for pulling the jenkins image out of the payload was that it allowed us to use the same jenkins CPaaS image across multiple OCP releases

**Comment by coreydaley** [comment]
> > @jkhelil Shouldn't we be using the 4.12 images on this branch?
> 
> I thought one of the big selling points for pulling the jenkins image out of the payload was that it allowed us to use the same jenkins CPaaS image across multiple OCP releases

It probably would if we had been able to get testing setup for it.

**Comment by gabemontero** [comment]
> > > @jkhelil Shouldn't we be using the 4.12 images on this branch?
> > 
> > 
> > I thought one of the big selling points for pulling the jenkins image out of the payload was that it allowed us to use the same jenkins CPaaS image across multiple OCP releases
> 
> It probably would if we had been able to get testing setup for it.

 the e2e-aws-jenkins test job here got you some amount of testing 

in theory you could add the sync and client pluging e2e's as optional tests in this repo

**Comment by jkhelil** [comment]
> > > > @jkhelil Shouldn't we be using the 4.12 images on this branch?
> > > 
@gabemontero yes we should, but I dont see the 4.12 is delivered here @gabemontero 
https://catalog.redhat.com/software/containers/ocp-tools-4/jenkins-rhel8/5fe1f38288e9c2f788526306?tag=all
I need to find out why we dont have it in the catalog

/hold

**Comment by coreydaley** [comment]
@jkhelil We can update this to 4.12 now, and then back port to 4.11 (which is still pointing to the old 4.10 imagestreams :( )

**Pull request closed without merging**
