### PR TITLE
Bug 1993840: more avoiding immediate degraded on intermittent API errors

### PR DESCRIPTION
**Pull request by gabemontero**
Missed some spots with https://github.com/openshift/cluster-samples-operator/pull/387/files

/assign @dperaza4dustbit

### CODE REVIEW

**Review by dperaza4dustbit — APPROVED** [review]
/lgtm

**Comment by gabemontero** [comment]
install / aws flake e2e-aws-image-ecosystem

various sig flakes upgrade

/retest

**Comment by gabemontero** [comment]
ingress / etcd flake

/test e2e-aws-image-ecosystem

**Pull request merged**
